In [1]:
import pandas as pd

In [17]:
#csv 폴더 안에 있는 Sales Records.csv 파일 로드
sales=pd.read_csv('../csv/Sales Records.csv')

In [18]:
#데이터 파일을 로드했으면 확인
sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Region          10000 non-null  str
 1   Country         10000 non-null  str
 2   Item Type       10000 non-null  str
 3   Sales Channel   10000 non-null  str
 4   Order Priority  10000 non-null  str
 5   Order Date      10000 non-null  str
 6   Order ID        10000 non-null  int64
 7   Ship Date       10000 non-null  str
 8   Units Sold      10000 non-null  int64
 9   Unit Price      10000 non-null  float64
 10  Unit Cost       10000 non-null  float64
 11  Total Revenue   10000 non-null  float64
 12  Total Cost      10000 non-null  float64
 13  Total Profit    10000 non-null  float64
dtypes: float64(5), int64(2), str(7)
memory usage: 1.1 MB

In [19]:
sales.describe()

,Order ID,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
count,1.000000e+04,10000.000000,10000.000000,10000.000000,1.000000e+04,1.000000e+04,1.000000e+04
mean,5.498719e+08,5002.855900,268.143139,188.806639,1.333355e+06,9.382658e+05,3.950893e+05
std,2.607835e+08,2873.246454,217.944092,176.445907,1.465026e+06,1.145914e+06,3.775550e+05
min,1.000892e+08,2.000000,9.330000,6.920000,1.679400e+02,1.245600e+02,4.338000e+01
25%,3.218067e+08,2530.750000,109.280000,56.670000,2.885511e+05,1.647855e+05,9.832914e+04
50%,5.485663e+08,4962.000000,205.700000,117.110000,8.000512e+05,4.816058e+05,2.890990e+05
75%,7.759981e+08,7472.000000,437.200000,364.690000,1.819143e+06,1.183822e+06,5.664227e+05
max,9.999342e+08,10000.000000,668.270000,524.960000,6.680027e+06,5.241726e+06,1.738178e+06

In [20]:
#데이터프레임의 상단의 5개 데이터 확인
sales.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit
0,Sub-Saharan Africa,Chad,Office Supplies,Online,L,1/27/2011,292494523,2/12/2011,4484,651.21,524.96,2920025.64,2353920.64,566105.00
1,Europe,Latvia,Beverages,Online,C,12/28/2015,361825549,1/23/2016,1075,47.45,31.79,51008.75,34174.25,16834.50
2,Middle East and North Africa,Pakistan,Vegetables,Offline,C,1/13/2011,141515767,2/1/2011,6515,154.06,90.93,1003700.90,592408.95,411291.95
3,Sub-Saharan Africa,Democratic Republic of the Congo,Household,Online,C,9/11/2012,500364005,10/6/2012,7683,668.27,502.54,5134318.41,3861014.82,1273303.59
4,Europe,Czech Republic,Beverages,Online,C,10/27/2015,127481591,12/5/2015,3491,47.45,31.79,165647.95,110978.89,54669.06

### 연습
1. 원본의 데이터의 복사본을 생성
2. 'Order ID', 'Total Revenue', 'Total Cost', 'Total Profit', 'Order Priority'컬럼을 제거
3. 컬럼의 이름을 변경 -> 대륙, 국가, 상품종류, 판매채널, 주문일자, 발송일자, 판매개수, 단가, 원가
4. 대륙, 국가를 기준으로 오름차순 정렬
5. 인덱스를 초기화하고 기존의 인덱스는 제거
6. 파생변수 생성
    - 총단가 = 단가 * 판매개수
    - 총원가 = 원가 * 판매개수
    - 총이윤 = 총단가 - 총원가

In [157]:
#원본 데이터의 복사본을 생성(copy() 함수를 호출하여 복사본을 생성)
df=sales.copy()
# 컬럼을 제거 
df.drop(
    ['Order ID', 'Total Revenue', 'Total Cost', 
     'Total Profit', 'Order Priority'], 
     axis = 1, inplace = True
)

In [158]:
#drop() 함수를 이용하여 컬럼을 제거한 데이터프레임을 새로운 변수에 대입
#(컬럼을 제거한다 + 복사본을 생성한다.)
df2=sales.drop(['Order ID', 'Total Revenue', 'Total Cost', 'Total Profit', 'Order Priority'],axis=1)

In [163]:
#컬럼의 이름을 변경 -> 2개의 방방(rename()함수 사용 / DataFrame.columns 변수의 데이터를 변경)
#rename() : 특정 컬럼의 이름을 변경할 때 주로 사용(컬럼의 이름이 변경된 데이터를 먼저 확인하고 사용)
#DataFrame.columns의 변수 데이터를 변경할 떄는 확인 후 변경이 불가능 (모든 컬럼의 이름을 변경)
# df[['Region','Country','Item Type','Sales Channel','Order Date','Ship Date','Units Sold','Unit Price','Unit Cost','Total Profit']]=['대륙', '국가', '상품종류', '판매채널', '주문일자', '발송일자', '판매개수', '단가', '원가']
df.rename(
    columns={
        'Region':'대륙',
        'Country':'국가',
        'Item Type':'상품종류',
        'Sales Channel':'판매채널',
        'Order Date':'주문일자',
        'Ship Date':'발송일자',
        'Units Sold':'판매개수',
        'Unit Price':'단가',
        'Unit Cost':'원가',
    },inplace=True
)

In [165]:
df2.columns=['대륙','국가','상품종류','판매채널','주문일자','발송일자','판매개수','단가','원가']
df2.head()

,대륙,국가,상품종류,판매채널,주문일자,발송일자,판매개수,단가,원가
0,Sub-Saharan Africa,Chad,Office Supplies,Online,1/27/2011,2/12/2011,4484,651.21,524.96
1,Europe,Latvia,Beverages,Online,12/28/2015,1/23/2016,1075,47.45,31.79
2,Middle East and North Africa,Pakistan,Vegetables,Offline,1/13/2011,2/1/2011,6515,154.06,90.93
3,Sub-Saharan Africa,Democratic Republic of the Congo,Household,Online,9/11/2012,10/6/2012,7683,668.27,502.54
4,Europe,Czech Republic,Beverages,Online,10/27/2015,12/5/2015,3491,47.45,31.79

In [166]:
#대륙, 국가를 기준으로 오름차순 정렬
#value를 기준으로 정렬을 변경 -> sort_values()
#잘못된 예시  ->
#       1. 대륙을 기준으로 오름차순을 정렬
#       2. 국가를 기준으로 오름차순을 정렬 -> 1번 작업과 상관없이 국가별로 오름차순
df.sort_values('대륙', inplace=True)
df.sort_values('국가', inplace=True)

In [167]:
df

,대륙,국가,상품종류,판매채널,주문일자,발송일자,판매개수,단가,원가
4027,Middle East and North Africa,Afghanistan,Cereal,Offline,7/24/2013,8/23/2013,9402,205.70,117.11
7271,Middle East and North Africa,Afghanistan,Office Supplies,Online,8/7/2013,9/20/2013,2660,651.21,524.96
3497,Middle East and North Africa,Afghanistan,Clothes,Online,5/4/2012,5/27/2012,8197,109.28,35.84
4053,Middle East and North Africa,Afghanistan,Beverages,Offline,4/22/2017,5/3/2017,2707,47.45,31.79
3500,Middle East and North Africa,Afghanistan,Baby Food,Offline,12/21/2015,12/21/2015,1368,255.28,159.42
...,...,...,...,...,...,...,...,...,...
136,Sub-Saharan Africa,Zimbabwe,Household,Offline,5/17/2016,7/1/2016,3726,668.27,502.54
9645,Sub-Saharan Africa,Zimbabwe,Cereal,Online,2/15/2010,3/1/2010,7309,205.70,117.11
9541,Sub-Saharan Africa,Zimbabwe,Fruits,Offline,11/20/2015,11/27/2015,5904,9.33,6.92
1915,Sub-Saharan Africa,Zimbabwe,Cereal,Online,8/21/2012,9/12/2012,83,205.70,117.11
3459,Sub-Saharan Africa,Zimbabwe,Snacks,Online,11/26/2010,1/3/2011,9765,152.58,97.44

In [170]:
#대륙별로 오름차순 정렬이 되고 대륙별 국가로 오름차순 정렬이 되는 방법
#sort_values함수에 기준이 2개
df.sort_values(['대륙','국가'],inplace=True)

In [171]:
#인덱스를 초기화하고 기존의 인덱스는 제거
#reset_index() : 기존의 인덱스를 제거한다, drop 매개변수 사용
df.reset_index(drop=True,inplace=True)

In [172]:
#파생변수 생성(총단가,총원가,총이윤)
#총단가, 총원가 -> 기존의 데이터에서 계산식
#총이윤 -> 파생변수에서 파생된 새로운 변수
df['총단가']=df['단가']*df['판매개수']
#행렬 간의 곱 -> Series, DataFrame이든 values의 타입은 행렬 -> value * value -> 행렬 * 행렬(두개의 행렬의 크기가 같아야 함)
df['총원가']=df['원가']*df['판매개수']
df['총이윤']=df['총단가']-df['총원가']
# df['총이윤']=(df['단가']*df['판매개수'])-(df['원가']*df['판매개수'])

In [174]:
df.head()

,대륙,국가,상품종류,판매채널,주문일자,발송일자,판매개수,단가,원가,총단가,총원가,총이윤
0,Asia,Bangladesh,Personal Care,Online,11/6/2010,11/13/2010,3246,81.73,56.67,265295.58,183950.82,81344.76
1,Asia,Bangladesh,Cereal,Online,11/20/2015,12/26/2015,2691,205.70,117.11,553538.70,315143.01,238395.69
2,Asia,Bangladesh,Office Supplies,Online,12/1/2016,1/20/2017,3907,651.21,524.96,2544277.47,2051018.72,493258.75
3,Asia,Bangladesh,Baby Food,Online,2/4/2016,3/4/2016,99,255.28,159.42,25272.72,15782.58,9490.14
4,Asia,Bangladesh,Fruits,Online,11/15/2011,11/16/2011,6729,9.33,6.92,62781.57,46564.68,16216.89

In [175]:
#어떤 대륙이 총이윤의 합계가 가장 클까?
#대륙별 고유값 리스트를 생성 -> unique() // value_counts()
#대륙 컬럼을 기준으로 비교연산자를 사용해서 필터링 -> 총이윤의 합산(반복실행)
df['대륙'].unique()

<StringArray>
[                             'Asia',             'Australia and Oceania',
 'Central America and the Caribbean',                            'Europe',
      'Middle East and North Africa',                     'North America',
                'Sub-Saharan Africa']
Length: 7, dtype: str

In [56]:
df2['대륙'].value_counts() #결과의 타임은 Series -> index의 값들은 추출하면 고유값 리스트

대륙
Europe                               2633
Sub-Saharan Africa                   2603
Asia                                 1469
Middle East and North Africa         1264
Central America and the Caribbean    1019
Australia and Oceania                 797
North America                         215
Name: count, dtype: int64

In [176]:
list_1=df['대륙'].value_counts().index

In [178]:
data_list=[]

for data in list_1:
    #data에 대입이 되는 데이터는 각 대륙의 이름
    # print(data)
    #조건식 생성
    flag=df['대륙']==data
    #조건식을 이용하여 필터 -> 총이윤의 합산
    result=df.loc[flag,'총이윤'].sum()
    # print(result)
    #대륙의 이름과 총이윤의 합산을 dict 형태로 새성하여 새로운 리스트에 추가
    dict_data={'대륙' : data, '총이윤 합산' : result}
    data_list.append(dict_data)
data_list

[{'대륙': 'Europe', '총이윤 합산': np.float64(1026999612.8)},
 {'대륙': 'Sub-Saharan Africa', '총이윤 합산': np.float64(999642091.5)},
 {'대륙': 'Asia', '총이윤 합산': np.float64(587403296.8499999)},
 {'대륙': 'Middle East and North Africa', '총이윤 합산': np.float64(509923894.53)},
 {'대륙': 'Central America and the Caribbean',
  '총이윤 합산': np.float64(403357849.72)},
 {'대륙': 'Australia and Oceania', '총이윤 합산': np.float64(324071211.41)},
 {'대륙': 'North America', '총이윤 합산': np.float64(99495515.12)}]

In [65]:
#data_list를 데이터프레임으로 변경
pd.DataFrame(data_list)

                                  대륙        총이윤 합산
0                             Europe  1.027000e+09
1                 Sub-Saharan Africa  9.996421e+08
2                               Asia  5.874033e+08
3       Middle East and North Africa  5.099239e+08
4  Central America and the Caribbean  4.033578e+08
5              Australia and Oceania  3.240712e+08
6                      North America  9.949552e+07

In [179]:
#데이터의 그룹화 -> 같은 데이터들을 결합하여 연산한 뒤 새로운 데이터로 구성
#그룹화 함수 : groupby(그룹화 할 컬럼의 이름(2개 이상이라면 []로 입력))

group_data=df.groupby('대륙')
group_data

In [181]:
#그룹화 데이터에서 특정 그룹만 추출 -> 그룹(group)ㅇ르 가져오다(get) -> get_group()
group_data.get_group('Asia')
#loc를 이용해서 대륙이 Asia와 같은 조건식을 필터링과 같은 데이터

,대륙,국가,상품종류,판매채널,주문일자,발송일자,판매개수,단가,원가,총단가,총원가,총이윤
0,Asia,Bangladesh,Personal Care,Online,11/6/2010,11/13/2010,3246,81.73,56.67,265295.58,183950.82,81344.76
1,Asia,Bangladesh,Cereal,Online,11/20/2015,12/26/2015,2691,205.70,117.11,553538.70,315143.01,238395.69
2,Asia,Bangladesh,Office Supplies,Online,12/1/2016,1/20/2017,3907,651.21,524.96,2544277.47,2051018.72,493258.75
3,Asia,Bangladesh,Baby Food,Online,2/4/2016,3/4/2016,99,255.28,159.42,25272.72,15782.58,9490.14
4,Asia,Bangladesh,Fruits,Online,11/15/2011,11/16/2011,6729,9.33,6.92,62781.57,46564.68,16216.89
...,...,...,...,...,...,...,...,...,...,...,...,...
1464,Asia,Vietnam,Clothes,Offline,11/6/2015,12/12/2015,4358,109.28,35.84,476242.24,156190.72,320051.52
1465,Asia,Vietnam,Beverages,Offline,1/10/2017,1/22/2017,1595,47.45,31.79,75682.75,50705.05,24977.70
1466,Asia,Vietnam,Vegetables,Offline,4/28/2012,6/6/2012,6219,154.06,90.93,958099.14,565493.67,392605.47
1467,Asia,Vietnam,Clothes,Online,2/1/2013,3/2/2013,8638,109.28,35.84,943960.64,309585.92,634374.72
1468,Asia,Vietnam,Office Supplies,Online,11/19/2016,12/21/2016,3669,651.21,524.96,2389289.49,1926078.24,463211.25

In [182]:
#그룹화된 데이터에서 그룹끼리의 연산(그룹화 연산)
group_data.sum()['총이윤']
#합산 -> 문자의 합산 -> 문자끼리의 연결
#숫재의 합산 -> 누적합

대륙
Asia                                 5.874033e+08
Australia and Oceania                3.240712e+08
Central America and the Caribbean    4.033578e+08
Europe                               1.027000e+09
Middle East and North Africa         5.099239e+08
North America                        9.949552e+07
Sub-Saharan Africa                   9.996421e+08
Name: 총이윤, dtype: float64

In [ ]:
#그룹화 연산의 평균
# group_data.mean()
#group_data에서 컬럼의 dtype이 숫자형이 아니라면 평균에서 에러 발생
#그룹화를 할때 문자열 컬럼은 제외하고 그룹화 -> 그룹화 연산

TypeError: dtype 'str' does not support operation 'mean'

In [183]:
# 컬럼을 필터(특정 컬럼들을 선택) -> 그룹화 -> 그룹화 연산
#대륙별 총 이윤의 합계와 평균을 구해보자.
#컬럼을 필터 -> 총이윤
# df2[['총이윤','대륙']].groupby('대륙').sum().mean()
#sum() -> mean()
#총이윤의 합산에서 평균
#합산 따로 평균 따로
group_data2=df[['총이윤','대륙']].groupby('대륙').agg(['mean','sum'])

In [184]:
#데이터프레임이 멀티 컬럼으로 이루어진 데이터프레임
#데이터에 접근하기 위한 방법은 컬럼도 하나씩 선택
#컬럼을 선택하기 위해서는 가장 상단의 컬럼부터 하나씩 선택
group_data2['총이윤']['mean']['Asia']

np.float64(399866.09724302246)

In [ ]:
test_data={
    '총이윤':{
        'mean':{
            'Asia':100
        },
        'sum':{
            'Asia':1000
        }
    }
}
#3차원 데이터에서 단일 데이터까지 추출(3번의 필터)
#test_data['총이윤]['mean']['Asia']
#에러발생 -> dict 데이터에서 key가 총이윤만 존재
# test_data['mean']

KeyError: 'mean'

In [185]:
#group_data2의 인덱스와 컬럼을 확인
print(group_data2.index)
print(group_data2.columns)

Index(['Asia', 'Australia and Oceania', 'Central America and the Caribbean',
       'Europe', 'Middle East and North Africa', 'North America',
       'Sub-Saharan Africa'],
      dtype='str', name='대륙')
MultiIndex([('총이윤', 'mean'),
            ('총이윤',  'sum')],
           )

In [186]:
group_data2[('총이윤','mean')]

대륙
Asia                                 399866.097243
Australia and Oceania                406613.816073
Central America and the Caribbean    395836.947713
Europe                               390049.226282
Middle East and North Africa         403420.802634
North America                        462769.837767
Sub-Saharan Africa                   384034.610642
Name: (총이윤, mean), dtype: float64

In [187]:
#멀티 인덱스를 생성
#그룹화기준 컬럼을 2개 이상(대륙, 판매채널)
#총 이윤의 합산
group_data3=df[['대륙','판매채널','총이윤']].groupby(['대륙','판매채널']).sum()

In [188]:
#유럽의 오프라인 총이윤의 합산을 추출
#하나씩 풀어나간다 -> 컬럼 -> 인덱스로 선택
group_data3['총이윤']['Europe']['Offline']

np.float64(533762385.78999996)

In [189]:
#loc를 이용해서 데이터 추출 -> index가 멀티
group_data3.loc[
    ('Europe','Offline'),'총이윤'
]

np.float64(533762385.78999996)

In [190]:
# iloc를 이용해서 데이터 추출 -> 위치를 기준으로 데이터 추출
group_data3.iloc[6,0]

np.float64(533762385.78999996)

In [191]:
#reset_index() -> 기존의 인덱스는 유지
group_data3.reset_index()

                                   대륙     판매채널           총이윤
0                                Asia  Offline  2.734457e+08
1                                Asia   Online  3.139576e+08
2               Australia and Oceania  Offline  1.527809e+08
3               Australia and Oceania   Online  1.712903e+08
4   Central America and the Caribbean  Offline  2.102715e+08
5   Central America and the Caribbean   Online  1.930864e+08
6                              Europe  Offline  5.337624e+08
7                              Europe   Online  4.932372e+08
8        Middle East and North Africa  Offline  2.549156e+08
9        Middle East and North Africa   Online  2.550083e+08
10                      North America  Offline  5.338042e+07
11                      North America   Online  4.611510e+07
12                 Sub-Saharan Africa  Offline  5.023457e+08
13                 Sub-Saharan Africa   Online  4.972964e+08

In [192]:
#인덱스 기준을 컬럼으로 올려서 새로운 데이터프레임 생성
group_data3.unstack()

                                            총이윤
판매채널                                    Offline        Online
대륙
Asia                               2.734457e+08  3.139576e+08
Australia and Oceania              1.527809e+08  1.712903e+08
Central America and the Caribbean  2.102715e+08  1.930864e+08
Europe                             5.337624e+08  4.932372e+08
Middle East and North Africa       2.549156e+08  2.550083e+08
North America                      5.338042e+07  4.611510e+07
Sub-Saharan Africa                 5.023457e+08  4.972964e+08

In [193]:
#컬럼의 기준을 인덱스로 이동
group_data3.stack()

대륙                                 판매채널
Asia                               Offline  총이윤    2.734457e+08
                                   Online   총이윤    3.139576e+08
Australia and Oceania              Offline  총이윤    1.527809e+08
                                   Online   총이윤    1.712903e+08
Central America and the Caribbean  Offline  총이윤    2.102715e+08
                                   Online   총이윤    1.930864e+08
Europe                             Offline  총이윤    5.337624e+08
                                   Online   총이윤    4.932372e+08
Middle East and North Africa       Offline  총이윤    2.549156e+08
                                   Online   총이윤    2.550083e+08
North America                      Offline  총이윤    5.338042e+07
                                   Online   총이윤    4.611510e+07
Sub-Saharan Africa                 Offline  총이윤    5.023457e+08
                                   Online   총이윤    4.972964e+08
dtype: float64

In [194]:
df[['총이윤']].groupby(df2['대륙']).sum()
#groupby()함수의 특징
#groupby(Series) -> 인덱스를 기준으로 데이터를 그룹화

                                            총이윤
대륙
Asia                               5.621700e+08
Australia and Oceania              3.096088e+08
Central America and the Caribbean  3.996975e+08
Europe                             1.041352e+09
Middle East and North Africa       4.997444e+08
North America                      8.637030e+07
Sub-Saharan Africa                 1.051951e+09

In [195]:
#stack(),unstack() : 인덱스를 컬럼으로 이동시키거나 컬럼을 인덱스로 이동
# 이동 시키고 컬럼이나 인덱스가 존재하지 않는 경우(ex : 싱글 컬럼은 인덱스로 이동)
# 데이터 타입이 스리즈의 형태로 변경

# 멀티 인덱스로 이루어진 스리즈에서 unstack()을 이용하면 데이터프레임으로 타입이 변경
group_data4=df.groupby(['대륙','판매채널'])['총이윤'].sum()

In [196]:
group_data4.unstack()

판매채널                                    Offline        Online
대륙
Asia                               2.734457e+08  3.139576e+08
Australia and Oceania              1.527809e+08  1.712903e+08
Central America and the Caribbean  2.102715e+08  1.930864e+08
Europe                             5.337624e+08  4.932372e+08
Middle East and North Africa       2.549156e+08  2.550083e+08
North America                      5.338042e+07  4.611510e+07
Sub-Saharan Africa                 5.023457e+08  4.972964e+08

In [197]:
#Series 데이터에서 stack() 사용하면? --> 에러발생(stack함수는 내장되어있지 않다.)
# group_data4.stack()

In [199]:
#pivot -> table의 데이터들을 재구조화 한다.
#pandas에서 pivot_table()
#pandas 안에 존재, 데이터프레임 안에서도 존재
#모듈 안에 있는 pivot_table()
#DataFrame class 안에 pivot_table()
#매개변수 index : 어떤 값을 기준(인덱스)으로 테이블 데이터를 배치할 것인가?(인덱스로 사용할 데이터 지정)
# 매개변수 columns : 어떤 값을 기준(컬럼)으로 테이블 데이터를 매치할것인가? (컬럼으로 사용할 데이터 지정) 
# 매개변수 values : index, columns를 기준으로 데이터를 결합하여 사용할 value는 무엇인가?
# 매개변수 aggfunc : values를 어떤 연산을 할 것인가?

In [200]:
#데이터프레임 클래스 안에 존재하는 pivot_table()함수 사용
df.pivot_table(
    index='대륙',
    values='총이윤',
    aggfunc='sum'
)

                                            총이윤
대륙
Asia                               5.874033e+08
Australia and Oceania              3.240712e+08
Central America and the Caribbean  4.033578e+08
Europe                             1.027000e+09
Middle East and North Africa       5.099239e+08
North America                      9.949552e+07
Sub-Saharan Africa                 9.996421e+08

In [201]:
df.pivot_table(
    index='대륙',
    columns='판매채널',
    values='총이윤',
    aggfunc=['sum','mean']
)

                                            sum                         mean  \
판매채널                                    Offline        Online        Offline
대륙
Asia                               2.734457e+08  3.139576e+08  386222.681285
Australia and Oceania              1.527809e+08  1.712903e+08  409600.378954
Central America and the Caribbean  2.102715e+08  1.930864e+08  406714.673849
Europe                             5.337624e+08  4.932372e+08  404979.048399
Middle East and North Africa       2.549156e+08  2.550083e+08  407864.945456
North America                      5.338042e+07  4.611510e+07  489728.620000
Sub-Saharan Africa                 5.023457e+08  4.972964e+08  389717.367285


판매채널                                      Online
대륙
Asia                               412559.314717
Australia and Oceania              403986.485991
Central America and the Caribbean  384634.189920
Europe                             375085.343734
Middle East and North Africa       399074.027574
North America                      435048.071132
Sub-Saharan Africa                 378459.973417

In [202]:
#라이브러리(pandas)안에 pivot_table() 함수 호출
pd.pivot_table(
    df,         #module 안에서 함수를 호출 시 변경할 데이터를 인자로 입력
    index='대륙',
    columns='판매채널',
    values='총이윤',
    aggfunc='sum'
)

판매채널                                    Offline        Online
대륙
Asia                               2.734457e+08  3.139576e+08
Australia and Oceania              1.527809e+08  1.712903e+08
Central America and the Caribbean  2.102715e+08  1.930864e+08
Europe                             5.337624e+08  4.932372e+08
Middle East and North Africa       2.549156e+08  2.550083e+08
North America                      5.338042e+07  4.611510e+07
Sub-Saharan Africa                 5.023457e+08  4.972964e+08

### 연습
1. 각 대륙별 총이윤이 가장 많은 아이템은 무엇인가?
    - 대륙,상품종류 별 그룹화
    - 그룹화 연산으로는 총이윤의 합계
    - 각 대륙별로 총이윤이 가장 높은 상품종류를 출력하시오.
        - 그룹화 -> 그룹화 연산 -> 총이윤을 기준으로 내림차순 -> 인덱스를 리셋 -> 반복문을 이용해서 각 대륙의 첫번째의 인덱스를 추출 -> 데이터프레임에 필터
    - 답안
        - Asia, Oceania, Europe, Saharan_Africa -> Cosmetic
        - America, North Africa -> Household

In [203]:
#반복문을 이용해서 각 대륙별 총이윤이 가장 높은 상품종류를 찾아보자.
group_data5=df[['대륙','상품종류','총이윤']].groupby(['대륙','총이윤']).sum()
group_data5

                                    상품종류
대륙                 총이윤
Asia               43.38          Fruits
                   62.64       Beverages
                   72.30          Fruits
                   125.28      Beverages
                   342.22         Fruits
...                                  ...
Sub-Saharan Africa 1710880.80  Cosmetics
                   1728441.67  Cosmetics
                   1730875.85  Cosmetics
                   1732614.55  Cosmetics
                   1732788.42  Cosmetics

[9919 rows x 1 columns]

In [204]:
#총이윤을 기준으로 내림차순 정렬
group_df=group_data5.sort_values('총이윤',ascending=False)

In [205]:
group_df.index

MultiIndex([(                             'Asia', 1738178.3899999997),
            (     'Middle East and North Africa', 1735396.4700000002),
            (               'Sub-Saharan Africa', 1732788.4200000004),
            (               'Sub-Saharan Africa', 1732614.5500000003),
            (                           'Europe',         1731397.46),
            (               'Sub-Saharan Africa',         1730875.85),
            (                             'Asia', 1728615.5399999996),
            (                           'Europe', 1728615.5399999996),
            (               'Sub-Saharan Africa', 1728441.6700000004),
            (                           'Europe', 1727572.3200000003),
            ...
            (     'Middle East and North Africa', 243.41000000000008),
            (               'Sub-Saharan Africa',              241.0),
            (                           'Europe', 191.72000000000003),
            ('Central America and the Caribbean', 171.10999999999996),
            (                             'Asia', 125.28000000000003),
            ('Central America and the Caribbean',  72.29999999999998),
            (                             'Asia',  72.29999999999998),
            (                             'Asia', 62.640000000000015),
            (               'Sub-Saharan Africa',  57.84000000000003),
            (                             'Asia', 43.379999999999995)],
           names=['대륙', '총이윤'], length=9919)

In [206]:
#멀티 인덱스에서 첫번째 인덱스만 만족하는 조건식?
group_df.loc[('Europe', ),]

C:\Users\user\AppData\Local\Temp\ipykernel_14440\2236484559.py:2: PerformanceWarning: indexing past lexsort depth may impact performance.
  group_df.loc[('Europe', ),]

                     상품종류
총이윤
1731397.46      Cosmetics
1728615.54      Cosmetics
1727572.32      Cosmetics
1713662.72      Cosmetics
1708620.49      Cosmetics
...                   ...
858.00               Meat
829.04             Fruits
660.34             Fruits
451.08      Personal Care
191.72          Baby Food

[2611 rows x 1 columns]

In [207]:
#idxmax() : 데이터 내에서 최댓값을 가지는 인덱스를 출력해준다.
group_df.reset_index(inplace=True)

In [208]:
group_df.loc[group_df['대륙']=='Asia',].index[0]

np.int64(0)

In [214]:
index_list=[]
#반목문을 이용해서 각 대륙의 데이터 추출하고 그중 첫번째 데이터를 확인
#가각 대륙의 고유값 변수를 이용해서 반복문을 살행
for name in group_df['대륙'].unique():
    # print(name)
    #group_df의 대륙 컬럼이 name과 같은 조건식을 생성
    flag=group_df['대륙']==name
    # print(group_df.loc[flag,].head(1))  #이 값들은 모두 group_df에 존재
    #인덱스들을 뽑아서 새로운 리스트로 만들면 loc를 이용해서 한번에 확인이 가능
    index_list.append(
        group_df.loc[flag,].index[0]
    )
index_list

[np.int64(0),
 np.int64(1),
 np.int64(2),
 np.int64(4),
 np.int64(10),
 np.int64(16),
 np.int64(22)]

In [215]:
group_df.loc[index_list,]

                                   대륙         총이윤       상품종류
0                                Asia  1738178.39  Cosmetics
1        Middle East and North Africa  1735396.47  Cosmetics
2                  Sub-Saharan Africa  1732788.42  Cosmetics
4                              Europe  1731397.46  Cosmetics
10                      North America  1719400.43  Cosmetics
16  Central America and the Caribbean  1707925.01  Cosmetics
22              Australia and Oceania  1691755.10  Cosmetics

In [217]:
#idxmax()함수를 이용 -> value가 최대인 인덱스를 출력
group_data5.sort_values('총이윤',ascending=False)

                                                   상품종류
대륙                                총이윤
Asia                              1738178.39  Cosmetics
Middle East and North Africa      1735396.47  Cosmetics
Sub-Saharan Africa                1732788.42  Cosmetics
                                  1732614.55  Cosmetics
Europe                            1731397.46  Cosmetics
...                                                 ...
Central America and the Caribbean 72.30          Fruits
Asia                              72.30          Fruits
                                  62.64       Beverages
Sub-Saharan Africa                57.84          Fruits
Asia                              43.38          Fruits

[9919 rows x 1 columns]

In [218]:
group_data5.idxmax()

상품종류    (Central America and the Caribbean, 477452.189...
dtype: object

In [219]:
group_data5.groupby(level=0).idxmax()

                                                                                상품종류
대륙
Asia                                                                  (Asia, 757.56)
Australia and Oceania                     (Australia and Oceania, 883.8200000000002)
Central America and the Caribbean  (Central America and the Caribbean, 477452.189...
Europe                                                  (Europe, 331811.27999999997)
Middle East and North Africa                (Middle East and North Africa, 46337.42)
North America                                    (North America, 13699.210000000003)
Sub-Saharan Africa                          (Sub-Saharan Africa, 234149.16999999998)

In [221]:
df3=pd.pivot_table(
    df,
    index=['대륙','상품종류'],
    values='총이윤',
    aggfunc='sum'
)
df3

                                             총이윤
대륙                 상품종류
Asia               Baby Food        6.379205e+07
                   Beverages        8.647186e+06
                   Cereal           5.369351e+07
                   Clothes          3.886401e+07
                   Cosmetics        1.036069e+08
...                                          ...
Sub-Saharan Africa Meat             5.721001e+07
                   Office Supplies  1.269636e+08
                   Personal Care    2.666266e+07
                   Snacks           6.142855e+07
                   Vegetables       6.197819e+07

[84 rows x 1 columns]

In [222]:
#상품의 종루가 몇개인가> 12개
df2['상품종류'].unique()

<StringArray>
['Office Supplies',       'Beverages',      'Vegetables',       'Household',
       'Baby Food',            'Meat',          'Cereal',         'Clothes',
          'Snacks',   'Personal Care',       'Cosmetics',          'Fruits']
Length: 12, dtype: str

In [223]:
df3.sort_values(['대륙','총이윤'],ascending=True)
#sort_values() -> value를 기준으로 차순 정렬
#pandas에서 sort_values에 인덱스를 넣어도 실행이 될 수 있도록 업데이트가 됨
#구버전에서는 해당 함수가 실행이 되지 않을 수 있다.

                                             총이윤
대륙                 상품종류
Asia               Fruits           1.252062e+06
                   Beverages        8.647186e+06
                   Personal Care    1.703025e+07
                   Meat             3.255046e+07
                   Snacks           3.443074e+07
...                                          ...
Sub-Saharan Africa Cereal           9.426100e+07
                   Baby Food        1.129722e+08
                   Office Supplies  1.269636e+08
                   Household        1.764783e+08
                   Cosmetics        1.766093e+08

[84 rows x 1 columns]

In [224]:
for i in range(len(df3)):
    if i%12 == 0:
        print(df3.iloc[[i,]])

#주의할 점 : sort_values() 함수에 인덱스 기준을 넣는 것(구버전 실행 불가)
#           모든 대륙에서 모든 상품의 종류 데이터가 존재하는지 확인하고 실행

                        총이윤
대륙   상품종류
Asia Baby Food  63792050.06
                                         총이윤
대륙                    상품종류
Australia and Oceania Baby Food  32462893.14
                                                    총이윤
대륙                                상품종류
Central America and the Caribbean Baby Food  32823901.9
                          총이윤
대륙     상품종류
Europe Baby Food  96873431.92
                                                총이윤
대륙                           상품종류
Middle East and North Africa Baby Food  51015541.68
                                 총이윤
대륙            상품종류
North America Baby Food  12385016.14
                                       총이윤
대륙                 상품종류
Sub-Saharan Africa Baby Food  1.129722e+08

In [225]:
df4=df2.reset_index()
#정렬에 기준이 되는 컬럼은 2개인데 하나는 오름차순 나머지 하나는 내림차순 정력로 하는 방법?
#대륙으로는 오름차순(True), 총이윤으로는 내림차순(False)
df4.sort_values(['대륙','총이윤'],ascending=[True,False],inplace=True)

KeyError: '총이윤'

In [ ]:
#df4를 그룹화 -> 대륙을 기준으로 그룹화를 하고 해당 데이터프레임들의 첫번째 데이터(상위 1개)만 추출
df4.groupby('대륙').head(1).sort_values('대륙')