In [7]:
import pandas as pd
import yfinance as yf
import invest

In [8]:
hynix=yf.Ticker('000660.KS')
df=hynix.history(period='10y')
df.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2016-05-30 00:00:00+09:00,25432.094956,25916.935587,25255.789271,25564.324219,5492886,0.0,0.0
2016-05-31 00:00:00+09:00,25255.786864,25564.321782,24859.099113,25299.863281,5414611,0.0,0.0
2016-06-01 00:00:00+09:00,25432.089570,25564.318805,25035.401864,25123.554688,3630711,0.0,0.0
2016-06-02 00:00:00+09:00,25211.705729,25608.393407,24682.788826,24726.865234,3443745,0.0,0.0
2016-06-03 00:00:00+09:00,24815.024209,25079.482726,24153.877916,24330.183594,3680988,0.0,0.0

In [9]:
#invest 라이브러리 안에 Investing class 생성
inv=invest.Investing(df,_col='Close',_start='2016-07-01')

In [10]:
rtn_df,acc_rtn=inv.boll()

acc_rtn

매수일 : 2017-02-27 00:00:00, 매수가 : 41090.37109375
매도일 : 2017-04-26 00:00:00, 매도가 : 47968.5390625, 수익율 : 1.167391235115815

c:\Users\user\OneDrive\Desktop\데이터 분석 부트캠프\데이터 분석\260528\invest\bollinger\__init__.py:77: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.167391235115815' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[i, 'rtn'] = rtn

매수일 : 2017-11-30 00:00:00, 매수가 : 68603.046875
매도일 : 2018-02-13 00:00:00, 매도가 : 70357.7890625, 수익율 : 1.0255781961214825
매수일 : 2018-07-23 00:00:00, 매수가 : 73979.8203125
매도일 : 2019-01-24 00:00:00, 매도가 : 65472.23046875, 수익율 : 0.8850012096837641
매수일 : 2019-02-28 00:00:00, 매수가 : 65007.875
매도일 : 2019-04-03 00:00:00, 매도가 : 74201.84375, 수익율 : 1.141428538465532
매수일 : 2019-05-09 00:00:00, 매수가 : 70579.9921875
매도일 : 2019-06-26 00:00:00, 매도가 : 63986.3359375, 수익율 : 0.9065789603308038
매수일 : 2019-08-06 00:00:00, 매수가 : 66865.2421875
매도일 : 2019-09-04 00:00:00, 매도가 : 74294.71875, 수익율 : 1.1111111890040966
매수일 : 2019-10-18 00:00:00, 매수가 : 71880.1484375
매도일 : 2019-12-13 00:00:00, 매도가 : 81631.328125, 수익율 : 1.1356588696527063
매수일 : 2020-02-28 00:00:00, 매수가 : 82501.59375
매도일 : 2020-06-03 00:00:00, 매도가 : 83252.453125, 수익율 : 1.0091011499399065
매수일 : 2020-08-05 00:00:00, 매수가 : 75743.78125
매도일 : 2020-09-18 00:00:00, 매도가 : 78559.5390625, 수익율 : 1.0371747721863305
매수일 : 2020-10-30 00:00:00, 매수가 : 74992.9140625
매도일 : 2020-11-16 00:00:00, 매도가 : 91981.296875, 수익율 : 1.2265331734987879
매수일 : 2021-01-29 00:00:00, 매수가 : 116153.234375
매도일 : 2021-02-22 00:00:00, 매도가 : 129427.8828125, 수익율 : 1.1142856547123163
매수일 : 2021-05-11 00:00:00, 매수가 : 116627.359375
매도일 : 2021-10-28 00:00:00, 매도가 : 100982.1875, 수익율 : 0.8658533301376138
매수일 : 2022-01-21 00:00:00, 매수가 : 114214.09375
매도일 : 2022-07-15 00:00:00, 매도가 : 95267.84375, 수익율 : 0.8341163565901866
매수일 : 2022-08-10 00:00:00, 매수가 : 88607.7734375
매도일 : 2023-01-09 00:00:00, 매도가 : 83643.1640625, 수익율 : 0.9439709499245931
매수일 : 2023-03-09 00:00:00, 매수가 : 83254.1328125
매도일 : 2023-05-17 00:00:00, 매도가 : 89691.1171875, 수익율 : 1.0773172953407248
매수일 : 2023-12-05 00:00:00, 매수가 : 123513.9609375
매도일 : 2023-12-14 00:00:00, 매도가 : 134109.296875, 수익율 : 1.0857824966269312
매수일 : 2024-07-17 00:00:00, 매수가 : 217417.421875
매도일 : 2024-09-27 00:00:00, 매도가 : 181531.515625, 수익율 : 0.8349446611015748
매수일 : 2024-11-14 00:00:00, 매수가 : 170864.8125
매도일 : 2025-01-06 00:00:00, 매도가 : 197334.046875, 수익율 : 1.1549133141441863
매수일 : 2025-04-04 00:00:00, 매수가 : 181114.6875
매도일 : 2025-05-12 00:00:00, 매도가 : 193838.421875, 수익율 : 1.070252360814194
매수일 : 2025-08-21 00:00:00, 매수가 : 243980.453125
매도일 : 2025-09-09 00:00:00, 매도가 : 287215.78125, 수익율 : 1.1772081638968388
매수일 : 2026-03-31 00:00:00, 매수가 : 806865.0625
매도일 : 2026-04-15 00:00:00, 매도가 : 1135810.125, 수익율 : 1.4076828676666118

np.float64(2.699098714478422)

In [11]:
inv.bnh()

np.float64(81.18941522990684)

In [12]:
mmt_df, mmt_rtn = inv.mmt()
mmt_rtn

c:\Users\user\OneDrive\Desktop\데이터 분석 부트캠프\데이터 분석\260528\invest\momentum\__init__.py:39: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['BF1']=df.shift(1)[col].fillna(0)
c:\Users\user\OneDrive\Desktop\데이터 분석 부트캠프\데이터 분석\260528\invest\momentum\__init__.py:40: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['BF2']=df.shift(_momentum)[col].fillna(0)
c:\Users\user\OneDrive\Desktop\데이터 분석 부트캠프\데이터 분석\260528\invest\momentum\__init__.py:58: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=_df2.loc[i,'BF1']/_df2.loc[i,'BF2']-_score
c:\Users\user\OneDrive\Desktop\데이터 분석 부트캠프\데이터 분석\260528\invest\momentum\__init__.py:58: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=_df2.loc[i,'BF1']/_df2.loc[i,'BF2']-_score
c:\Users\user\OneDrive\Desktop\데이터 분석 부트캠프\데이터 분석\260528\invest\momentum\__init__.py:58: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=_df2.loc[i,'BF1']/_df2.loc[i,'BF2']-_score
c:\Users\user\OneDrive\Desktop\데이터 분석 부트캠프\데이터 분석\260528\invest\momentum\__init__.py:58: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=_df2.loc[i,'BF1']/_df2.loc[i,'BF2']-_score
c:\Users\user\OneDrive\Desktop\데이터 분석 부트캠프\데이터 분석\260528\invest\momentum\__init__.py:58: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=_df2.loc[i,'BF1']/_df2.loc[i,'BF2']-_score
c:\Users\user\OneDrive\Desktop\데이터 분석 부트캠프\데이터 분석\260528\invest\momentum\__init__.py:58: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=_df2.loc[i,'BF1']/_df2.loc[i,'BF2']-_score
c:\Users\user\OneDrive\Desktop\데이터 분석 부트캠프\데이터 분석\260528\invest\momentum\__init__.py:58: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=_df2.loc[i,'BF1']/_df2.loc[i,'BF2']-_score
c:\Users\user\OneDrive\Desktop\데이터 분석 부트캠프\데이터 분석\260528\invest\momentum\__init__.py:58: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=_df2.loc[i,'BF1']/_df2.loc[i,'BF2']-_score
c:\Users\user\OneDrive\Desktop\데이터 분석 부트캠프\데이터 분석\260528\invest\momentum\__init__.py:58: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=_df2.loc[i,'BF1']/_df2.loc[i,'BF2']-_score
c:\Users\user\OneDrive\Desktop\데이터 분석 부트캠프\데이터 분석\260528\invest\momentum\__init__.py:58: RuntimeWarning: divide by zero encountered in scalar divide
  momentum_index=_df2.loc[i,'BF1']/_df2.loc[i,'BF2']-_score

날짜 : 2016-07-29 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 2016-08-31 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 2016-09-30 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 2016-10-31 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 2016-11-30 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 2016-12-29 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 2017-01-31 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 2017-02-28 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 2017-03-31 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 2017-04-28 00:00:00, 모멘텀 인덱스 : inf, signal :
날짜 : 2017-05-31 00:00:00, 모멘텀 인덱스 : 0.9065925658874454, signal : buy
날짜 : 2017-06-30 00:00:00, 모멘텀 인덱스 : 0.7826899942394077, signal : buy
날짜 : 2017-07-31 00:00:00, 모멘텀 인덱스 : 0.9853971854644268, signal : buy
날짜 : 2017-08-31 00:00:00, 모멘텀 인덱스 : 0.8348157370354463, signal : buy
날짜 : 2017-09-29 00:00:00, 모멘텀 인덱스 : 0.7291956708026979, signal : buy
날짜 : 2017-10-31 00:00:00, 모멘텀 인덱스 : 1.0488811591045124, signal : buy
날짜 : 2017-11-30 00:00:00, 모멘텀 인덱스 : 0.9416034855660351, signal : buy
날짜 : 2017-12-28 00:00:00, 모멘텀 인덱스 : 0.7181204665767156, signal : buy
날짜 : 2018-01-31 00:00:00, 모멘텀 인덱스 : 0.44409576393902706, signal : buy
날짜 : 2018-02-28 00:00:00, 모멘텀 인덱스 : 0.5954356553119888, signal : buy
날짜 : 2018-03-30 00:00:00, 모멘텀 인덱스 : 0.5416243006907928, signal : buy
날짜 : 2018-04-30 00:00:00, 모멘텀 인덱스 : 0.5261794257334786, signal : buy
날짜 : 2018-05-31 00:00:00, 모멘텀 인덱스 : 0.5027641857275034, signal : buy
날짜 : 2018-06-29 00:00:00, 모멘텀 인덱스 : 0.4047395084430352, signal : buy
날짜 : 2018-07-31 00:00:00, 모멘텀 인덱스 : 0.3162719001104841, signal : buy
날짜 : 2018-08-31 00:00:00, 모멘텀 인덱스 : 0.27525059870345525, signal : buy
날짜 : 2018-09-28 00:00:00, 모멘텀 인덱스 : 0.014921203516235826, signal : buy
날짜 : 2018-10-31 00:00:00, 모멘텀 인덱스 : -0.09852382583826136, signal :
날짜 : 2018-11-30 00:00:00, 모멘텀 인덱스 : -0.09981431901598758, signal :
날짜 : 2018-12-28 00:00:00, 모멘텀 인덱스 : -0.09019580996737342, signal :
날짜 : 2019-01-31 00:00:00, 모멘텀 인덱스 : -0.15580097046635888, signal :
날짜 : 2019-02-28 00:00:00, 모멘텀 인덱스 : -0.013129278853547866, signal :
날짜 : 2019-03-29 00:00:00, 모멘텀 인덱스 : -0.11695201120061616, signal :
날짜 : 2019-04-30 00:00:00, 모멘텀 인덱스 : -0.09941657860209618, signal :
날짜 : 2019-05-31 00:00:00, 모멘텀 인덱스 : -0.13252477945591423, signal :
날짜 : 2019-06-28 00:00:00, 모멘텀 인덱스 : -0.21853548845911297, signal :
날짜 : 2019-07-31 00:00:00, 모멘텀 인덱스 : -0.17405541332552732, signal :
날짜 : 2019-08-30 00:00:00, 모멘텀 인덱스 : -0.0497781102301309, signal :
날짜 : 2019-09-30 00:00:00, 모멘텀 인덱스 : 0.08592689969303513, signal : buy
날짜 : 2019-10-31 00:00:00, 모멘텀 인덱스 : 0.23613042187614552, signal : buy
날짜 : 2019-11-29 00:00:00, 모멘텀 인덱스 : 0.20831814278696248, signal : buy
날짜 : 2019-12-30 00:00:00, 모멘텀 인덱스 : 0.3371901249337954, signal : buy
날짜 : 2020-01-31 00:00:00, 모멘텀 인덱스 : 0.2869172663234072, signal : buy
날짜 : 2020-02-28 00:00:00, 모멘텀 인덱스 : 0.3499544766691727, signal : buy
날짜 : 2020-03-31 00:00:00, 모멘텀 인덱스 : 0.19726552557524046, signal : buy
날짜 : 2020-04-29 00:00:00, 모멘텀 인덱스 : 0.0656714571083159, signal : buy
날짜 : 2020-05-29 00:00:00, 모멘텀 인덱스 : 0.29544148702087725, signal : buy
날짜 : 2020-06-30 00:00:00, 모멘텀 인덱스 : 0.18516345584772687, signal : buy
날짜 : 2020-07-31 00:00:00, 모멘텀 인덱스 : 0.11842968040815549, signal : buy
날짜 : 2020-08-31 00:00:00, 모멘텀 인덱스 : 0.0811721203883331, signal : buy
날짜 : 2020-09-29 00:00:00, 모멘텀 인덱스 : -0.0766347819448131, signal :
날짜 : 2020-10-30 00:00:00, 모멘텀 인덱스 : 0.035311334793200144, signal : buy
날짜 : 2020-11-30 00:00:00, 모멘텀 인덱스 : -0.0018318116935845952, signal :
날짜 : 2020-12-30 00:00:00, 모멘텀 인덱스 : 0.036131680799712296, signal : buy
날짜 : 2021-01-29 00:00:00, 모멘텀 인덱스 : 0.28034924297038843, signal : buy
날짜 : 2021-02-26 00:00:00, 모멘텀 인덱스 : 0.40789079453389343, signal : buy
날짜 : 2021-03-31 00:00:00, 모멘텀 인덱스 : 0.7160631698183495, signal : buy
날짜 : 2021-04-30 00:00:00, 모멘텀 인덱스 : 0.5992344977997879, signal : buy
날짜 : 2021-05-31 00:00:00, 모멘텀 인덱스 : 0.586624779204836, signal : buy
날짜 : 2021-06-30 00:00:00, 모멘텀 인덱스 : 0.5076344307515768, signal : buy
날짜 : 2021-07-30 00:00:00, 모멘텀 인덱스 : 0.5556129904450327, signal : buy
날짜 : 2021-08-31 00:00:00, 모멘텀 인덱스 : 0.5133328345760702, signal : buy
날짜 : 2021-09-30 00:00:00, 모멘텀 인덱스 : 0.28083176793195896, signal : buy
날짜 : 2021-10-29 00:00:00, 모멘텀 인덱스 : 0.3023036655650695, signal : buy
날짜 : 2021-11-30 00:00:00, 모멘텀 인덱스 : 0.06722120459611847, signal : buy
날짜 : 2021-12-30 00:00:00, 모멘텀 인덱스 : -0.03797459905132339, signal :
날짜 : 2022-01-28 00:00:00, 모멘텀 인덱스 : 0.08246225655306905, signal : buy
날짜 : 2022-02-28 00:00:00, 모멘텀 인덱스 : -0.13799845949704703, signal :
날짜 : 2022-03-31 00:00:00, 모멘텀 인덱스 : -0.060348556484502214, signal :
날짜 : 2022-04-29 00:00:00, 모멘텀 인덱스 : -0.06451553101249208, signal :
날짜 : 2022-05-31 00:00:00, 모멘텀 인덱스 : -0.10109594185045145, signal :
날짜 : 2022-06-30 00:00:00, 모멘텀 인덱스 : -0.1404359081102312, signal :
날짜 : 2022-07-29 00:00:00, 모멘텀 인덱스 : -0.1765772672663083, signal :
날짜 : 2022-08-31 00:00:00, 모멘텀 인덱스 : -0.06423441015278064, signal :
날짜 : 2022-09-30 00:00:00, 모멘텀 인덱스 : -0.059121262459269075, signal :
날짜 : 2022-10-31 00:00:00, 모멘텀 인덱스 : -0.17566215452381395, signal :
날짜 : 2022-11-30 00:00:00, 모멘텀 인덱스 : -0.25878860513281887, signal :
날짜 : 2022-12-29 00:00:00, 모멘텀 인덱스 : -0.3450448814192397, signal :
날짜 : 2023-01-31 00:00:00, 모멘텀 인덱스 : -0.3692843941506436, signal :
날짜 : 2023-02-28 00:00:00, 모멘텀 인덱스 : -0.2708827116052591, signal :
날짜 : 2023-03-31 00:00:00, 모멘텀 인덱스 : -0.23417827912351885, signal :
날짜 : 2023-04-28 00:00:00, 모멘텀 인덱스 : -0.20116828662457897, signal :
날짜 : 2023-05-31 00:00:00, 모멘텀 인덱스 : -0.1594312128489841, signal :
날짜 : 2023-06-30 00:00:00, 모멘텀 인덱스 : 0.2066827075223443, signal : buy
날짜 : 2023-07-31 00:00:00, 모멘텀 인덱스 : 0.19293272739719192, signal : buy
날짜 : 2023-08-31 00:00:00, 모멘텀 인덱스 : 0.3140875726915031, signal : buy
날짜 : 2023-09-27 00:00:00, 모멘텀 인덱스 : 0.4804197343947736, signal : buy
날짜 : 2023-10-31 00:00:00, 모멘텀 인덱스 : 0.40446715380567233, signal : buy
날짜 : 2023-11-30 00:00:00, 모멘텀 인덱스 : 0.385525272455872, signal : buy
날짜 : 2023-12-28 00:00:00, 모멘텀 인덱스 : 0.800850645266872, signal : buy
날짜 : 2024-01-31 00:00:00, 모멘텀 인덱스 : 0.6162079517642527, signal : buy
날짜 : 2024-02-29 00:00:00, 모멘텀 인덱스 : 0.5230494827351821, signal : buy
날짜 : 2024-03-29 00:00:00, 모멘텀 인덱스 : 0.7759445605326099, signal : buy
날짜 : 2024-04-30 00:00:00, 모멘텀 인덱스 : 1.0631455519784412, signal : buy
날짜 : 2024-05-31 00:00:00, 모멘텀 인덱스 : 0.6185276828536497, signal : buy
날짜 : 2024-06-28 00:00:00, 모멘텀 인덱스 : 0.6528330241538407, signal : buy
날짜 : 2024-07-31 00:00:00, 모멘텀 인덱스 : 0.9311960480632977, signal : buy
날짜 : 2024-08-30 00:00:00, 모멘텀 인덱스 : 0.609925985114431, signal : buy
날짜 : 2024-09-30 00:00:00, 모멘텀 인덱스 : 0.5220598920098973, signal : buy
날짜 : 2024-10-31 00:00:00, 모멘텀 인덱스 : 0.5114046050622434, signal : buy
날짜 : 2024-11-29 00:00:00, 모멘텀 인덱스 : 0.40071072481751346, signal : buy
날짜 : 2024-12-30 00:00:00, 모멘텀 인덱스 : 0.13522648267558313, signal : buy
날짜 : 2025-01-31 00:00:00, 모멘텀 인덱스 : 0.29694795506795213, signal : buy
날짜 : 2025-02-28 00:00:00, 모멘텀 인덱스 : 0.2811466597017236, signal : buy
날짜 : 2025-03-31 00:00:00, 모멘텀 인덱스 : 0.04912937787512006, signal : buy
날짜 : 2025-04-30 00:00:00, 모멘텀 인덱스 : 0.10502507235159109, signal : buy
날짜 : 2025-05-30 00:00:00, 모멘텀 인덱스 : -0.05300674935086913, signal :
날짜 : 2025-06-30 00:00:00, 모멘텀 인덱스 : -0.12669597304333302, signal :
날짜 : 2025-07-31 00:00:00, 모멘텀 인덱스 : 0.5154560732543201, signal : buy
날짜 : 2025-08-29 00:00:00, 모멘텀 인덱스 : 0.5902330234515965, signal : buy
날짜 : 2025-09-30 00:00:00, 모멘텀 인덱스 : 0.5556694001758713, signal : buy
날짜 : 2025-10-31 00:00:00, 모멘텀 인덱스 : 0.8834374260150522, signal : buy
날짜 : 2025-11-28 00:00:00, 모멘텀 인덱스 : 2.5299830934010443, signal : buy
날짜 : 2025-12-30 00:00:00, 모멘텀 인덱스 : 2.079615550501686, signal : buy
날짜 : 2026-01-30 00:00:00, 모멘텀 인덱스 : 2.302264535930481, signal : buy
날짜 : 2026-02-27 00:00:00, 모멘텀 인덱스 : 3.798161035809885, signal : buy
날짜 : 2026-03-31 00:00:00, 모멘텀 인덱스 : 4.596117209396329, signal : buy
날짜 : 2026-04-30 00:00:00, 모멘텀 인덱스 : 3.5729583579370496, signal : buy
날짜 : 2026-05-29 00:00:00, 모멘텀 인덱스 : 5.3137309783009, signal : buy
매수일 : 2017-05-31 00:00:00, 매수가 : 50916.328125

c:\Users\user\OneDrive\Desktop\데이터 분석 부트캠프\데이터 분석\260528\invest\momentum\__init__.py:75: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '1.212881657866997' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[i,'rtn']=rtn

매도일 : 2018-10-31 00:00:00, 매도가 : 50916.328125, 수익율 : 1.212881657866997
매수일 : 2019-09-30 00:00:00, 매수가 : 76337.828125
매도일 : 2020-09-29 00:00:00, 매도가 : 76337.828125, 수익율 : 1.032792044245757
매수일 : 2020-10-30 00:00:00, 매수가 : 74992.9140625
매도일 : 2020-11-30 00:00:00, 매도가 : 74992.9140625, 수익율 : 1.2202752905925591
매수일 : 2020-12-30 00:00:00, 매수가 : 112360.46875
매도일 : 2021-12-30 00:00:00, 매도가 : 112360.46875, 수익율 : 1.1190011361313408
매수일 : 2022-01-28 00:00:00, 매수가 : 115653.75
매도일 : 2022-02-28 00:00:00, 매도가 : 115653.75, 수익율 : 1.0207470709985624
매수일 : 2023-06-30 00:00:00, 매수가 : 112726.9609375
매도일 : 2025-05-30 00:00:00, 매도가 : 112726.9609375, 수익율 : 1.8065687064242826
매수일 : 2025-07-31 00:00:00, 매수가 : 272361.84375

np.float64(3.1542221883535633)

In [13]:
mmt_df

                   Close   STD-YM trade  rtn   acc_rtn
Date
2016-05-30  2.556432e+04  2016-05        1.0  1.000000
2016-05-31  2.529986e+04  2016-05        1.0  1.000000
2016-06-01  2.512355e+04  2016-06        1.0  1.000000
2016-06-02  2.472687e+04  2016-06        1.0  1.000000
2016-06-03  2.433018e+04  2016-06        1.0  1.000000
...                  ...      ...   ...  ...       ...
2026-05-22  1.940676e+06  2026-05   buy  1.0  3.154222
2026-05-26  2.051657e+06  2026-05   buy  1.0  3.154222
2026-05-27  2.242625e+06  2026-05   buy  1.0  3.154222
2026-05-28  2.289000e+06  2026-05   buy  1.0  3.154222
2026-05-29  2.301000e+06  2026-05   buy  1.0  3.154222

[2448 rows x 5 columns]