### 데이터 분할
- 분석 모델을 학습하고 성과를 확인하기 위해서 데이터를 train, test 세트로 나눠주고 나눠주는 작업
- 독립변수(x) -> 문제, 종속변수(y) -> 정답
- 독립변수와 종속변수 모두 train,test 데이터로 나눠준다.
- 분리 방법이나 데이터의 양에 따라서 Train, Validation, Test로 나눠주는 경우도 발생
- 데이터를 분할하는 일반적인 비율
    - Train : Test = 7 : 3 // 8 : 2
        - 가장 일반적인 분할 비율
    - Train : Validation : Test = 6 : 2 : 2 // 5 : 3 : 2
        - 데이터의 양이 많은 경우 검증 셋을 생성하여 2번의 검증 작업
    - kfold를 이용하면 여러번의 작업을 하여 검증이 가능
    - 유의할 점
        - 데이터의 불균형 문제
        - 데이터의 균형을 알맞게 분할하는 작업이 필요
- sklearn안에 train_test_split() 함수를 이용하여 데이터를 분할
    - train_test_split(X, y, test_size=None, random_state=None, shuffle=True, stratify=None)
        - X : 독립변수(문제)
        - y : 종속변수(정답)
        - test_size : 테스트 데이터의 비율(0부터 1사이의 값)
        - random_state : 임의의 데이터를 추출하는 과정에서 seed 값을 지정 (같은 값을 지정하면 규칙이 생성되어 같은 데이터를 확인)
        - shuffle : 데이터를 섞을 것인가(시계열 데이터인 경우에는 False)
        - stratify : 특정 변수를 지정하면 지정한 변수를 기준으로 하여 계층화 되어 해당 변수의 비율을 유지하도록 데이터 분할

In [2]:
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

In [3]:
#샘플 데이터셋 로드
iris_data=load_iris()

In [4]:
iris_data['frame']

In [5]:
#데이터프레임으로 변경
iris=pd.DataFrame(iris_data['data'],columns=iris_data['feature_names'])

#target 데이터 데이터프레임에 추가
iris['class']=iris_data['target']

iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),class
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [6]:
#target 데이터를 변환
iris['class']=iris['class'].map(
    lambda x : iris_data['target_names'][x]
)

In [7]:
iris.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),class
0,5.1,3.5,1.4,0.2,setosa
1,4.9,3.0,1.4,0.2,setosa
2,4.7,3.2,1.3,0.2,setosa
3,4.6,3.1,1.5,0.2,setosa
4,5.0,3.6,1.4,0.2,setosa

In [8]:
#class 컬럼의 데이터의 빈도수를 확인
iris['class'].value_counts()

class
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [9]:
#종속변수, 독립변수 데이터를 나눠서 train_test_split() 입력
X=iris.drop('class',axis=1)
y=iris['class']

In [10]:
#train_test_split() -> 결과물(train_x,train_y,test_x,test_y)
X_train,X_test,y_train,y_test=train_test_split(
    X, y, test_size=0.2,random_state=42
)

In [11]:
#데이터의 개수를 확인
print(f'X_train : {X_train.shape}, X_test : {X_test.shape}')
print(f'y_train : {y_train.shape}, y_test : {y_test.shape}')

X_train : (120, 4), X_test : (30, 4)
y_train : (120,), y_test : (30,)

In [12]:
y_train.value_counts()

class
versicolor    41
setosa        40
virginica     39
Name: count, dtype: int64

In [13]:
X_train.value_counts()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
5.8                2.7               5.1                1.9                 2
4.4                2.9               1.4                0.2                 1
4.3                3.0               1.1                0.1                 1
4.4                3.2               1.3                0.2                 1
4.5                2.3               1.3                0.3                 1
                                                                           ..
7.4                2.8               6.1                1.9                 1
7.6                3.0               6.6                2.1                 1
7.7                2.8               6.7                2.0                 1
                   3.0               6.1                2.3                 1
                   3.8               6.7                2.2                 1
Name: count, Length: 119, dtype: int64

In [14]:
#shuffle을 False로 바꿔서 사용하게 되면?
X_train2,X_test2,y_train2,y_test2=train_test_split(
    X, y, test_size=0.3,shuffle=False
)

In [16]:
X_train2.shape

(105, 4)

In [18]:
y_train2.value_counts()

class
setosa        50
versicolor    50
virginica      5
Name: count, dtype: int64

In [ ]:
iris.loc[:104,'class'].value_counts()

class
setosa        50
versicolor    50
virginica      5
Name: count, dtype: int64

In [19]:
#데이터 비율에 맞춰서 분할
X_train3,X_test3,y_train3,y_test3=train_test_split(
    X, y, test_size=0.2,shuffle=True
)

In [21]:
X_train3

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
125                7.2               3.2                6.0               1.8
128                6.4               2.8                5.6               2.1
134                6.1               2.6                5.6               1.4
89                 5.5               2.5                4.0               1.3
35                 5.0               3.2                1.2               0.2
..                 ...               ...                ...               ...
57                 4.9               2.4                3.3               1.0
11                 4.8               3.4                1.6               0.2
94                 5.6               2.7                4.2               1.3
23                 5.1               3.3                1.7               0.5
114                5.8               2.8                5.1               2.4

[120 rows x 4 columns]

In [22]:
y_train3

125     virginica
128     virginica
134     virginica
89     versicolor
35         setosa
          ...
57     versicolor
11         setosa
94     versicolor
23         setosa
114     virginica
Name: class, Length: 120, dtype: object

In [23]:
y_train3.value_counts()

class
virginica     45
setosa        38
versicolor    37
Name: count, dtype: int64

In [ ]:
# 계층화 작업을 하면 shuffle은 무조건 True로 사용
# X_train4,X_test4,y_train4,y_test4=train_test_split(
#     X, y, test_size=0.3,shuffle=False, stratify=y
# )

In [26]:
y_train2

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
100    virginica
101    virginica
102    virginica
103    virginica
104    virginica
Name: class, Length: 105, dtype: object

### 스케일링
- 
    1.

### Standard Scaler
- 표준화 방식으로 가장 기본적인 스케일러
- 평균이 0, 분산이 1인 정규분포로 스케일링
- 최솟값과 최댓값의 크기를 따로 제한하지 않아 이상치에 민감하기 때문에 이상치에 대한 확인 및 정제를 한 뒤 사용
- 일반적으로 회귀 분석보다는 분류 분석에서 사용

In [27]:
from sklearn.preprocessing import StandardScaler

In [28]:
#class 생성
stdscaler = StandardScaler()

In [29]:
#X_train3 데이터의 범위를 등록
#Scaler에서 fit() : 범윌을 지정 // transform() : 지정된 범위를 스케일링
#fit_transform() : fit() + transform()
#train data : fit() -> transform() || fit_transform()
#test_data : transform()
stdscaler.fit(X_train3)

StandardScaler()

In [30]:
#train 데이터 스케일링(변환) -> 따로 제공(함수의 맅ㄴ 데이터를 이용하여 원본 데이터를 변화시키지 않고 유지)
X_train_sc=stdscaler.transform(X_train3)

In [31]:
#test 데이터 스케일링
X_test_sc=stdscaler.transform(X_test3)

In [37]:
#데이터들의 최솟값과 최댓값, 평균, 표준편차를 출력하는 함수를 생성
def scaler_print(train,test):
    print(f'''
        Train Data : 
          Min : {round(train.min(),2)}
          Max : {round(train.max(),2)}
          Mean : {round(train.mean(),2)}
          Std : {round(train.std(),2)}

''')
    print(f'''
        Test Data : 
          Min : {round(test.min(),2)}
          Max : {round(test.max(),2)}
          Mean : {round(test.mean(),2)}
          Std : {round(test.std(),2)}


''')

In [38]:
scaler_print(X_train_sc,X_test_sc)

        Train Data :
          Min : -2.44
          Max : 3.06
          Mean : 0.0
          Std : 1.0



        Test Data :
          Min : -1.98
          Max : 1.91
          Mean : -0.26
          Std : 0.88

In [39]:
x_tr_s=stdscaler.fit_transform(X_train3)
x_te_s=stdscaler.fit_transform(X_test3)

scaler_print(x_tr_s,x_te_s)

        Train Data :
          Min : -2.44
          Max : 3.06
          Mean : 0.0
          Std : 1.0



        Test Data :
          Min : -1.98
          Max : 2.05
          Mean : -0.0
          Std : 1.0

In [41]:
scaler_print(X_train3.values,X_test3.values)

        Train Data :
          Min : 0.1
          Max : 7.9
          Mean : 3.52
          Std : 1.99



        Test Data :
          Min : 0.1
          Max : 6.9
          Mean : 3.24
          Std : 1.88

### Min-Max Scaler
- 정규화 방식으로 컬럼의 데이터들을 0과 1 사이의 값으로 스케일링하는 방식
- 최솟값은 0, 최댓값은 1
- 이상치 매우 민감함으로 이상치 대한 확인 및 정제 필수
- 일반적으러 분류 분석 보다는 회귀 분석에서 사용

In [43]:
from sklearn.preprocessing import MinMaxScaler

mnscaler=MinMaxScaler()

X_train_sc=mnscaler.fit_transform(X_train3)
X_test_sc=mnscaler.fit_transform(X_test3)

scaler_print(X_train_sc,X_test_sc)

        Train Data :
          Min : 0.0
          Max : 1.0
          Mean : 0.46
          Std : 0.27



        Test Data :
          Min : 0.0
          Max : 1.0
          Mean : 0.49
          Std : 0.3

### Max Abs Scaler
- 최대 절댓값과 0 이 각각 1, 0이 되도록 스케일링하는 정규화 방식으로 모든 값은 -1부터 1 사이로 표현
- 스케일링 대상의 데이터가 모두 양수라면 MinMaxScaler와 동일
- 이상치 매우 민감하기 때문에 확인 및 정제 작업 필요
- 일반적으로는 분류 분석보다 회귀 분석에서 사용

In [44]:
from sklearn.preprocessing import MaxAbsScaler
mascaler=MaxAbsScaler()
X_train_sc=mascaler.fit_transform(X_train3)
X_test_sc=mascaler.transform(X_test3)

scaler_print(X_train_sc,X_test_sc)

        Train Data :
          Min : 0.04
          Max : 1.0
          Mean : 0.63
          Std : 0.24



        Test Data :
          Min : 0.04
          Max : 0.89
          Mean : 0.57
          Std : 0.23

### Robust Scaler
- 평균과 분산을 이용한 Standard 대신에 중앙값과 사분위수를 활용하는 방식
- 중앙값을 0으로 설정, IQR을 사용하여 이상치의 영향을 최소화
- quantile_range 매개변수 (기본값[0.25, 0.75])의 값을 조정하여 더 넓거나 좁은 범위의 값을 이상치로 판단하게 하여 정제할 수 있다.

In [48]:
from sklearn.preprocessing import RobustScaler
ruscaler = RobustScaler()
ruscaler2 = RobustScaler(quantile_range=(0.2, 0.8))

In [49]:
ruscaler.fit(X_train3)

RobustScaler()

In [50]:
ruscaler2.fit(X_train3)

RobustScaler(quantile_range=(0.2, 0.8))

In [51]:
X_train_sc=ruscaler.fit_transform(X_train3)
X_test_sc=ruscaler.transform(X_test3)

scaler_print(X_train_sc,X_test_sc)

        Train Data :
          Min : -2.0
          Max : 2.8
          Mean : -0.02
          Std : 0.66



        Test Data :
          Min : -1.6
          Max : 1.8
          Mean : -0.16
          Std : 0.6

In [52]:
X_train_sc=ruscaler2.fit_transform(X_train3)
X_test_sc=ruscaler2.transform(X_test3)

scaler_print(X_train_sc,X_test_sc)

        Train Data :
          Min : -24.16
          Max : 17.16
          Mean : -0.92
          Std : 6.74



        Test Data :
          Min : -23.46
          Max : 7.35
          Mean : -2.07
          Std : 6.58

In [53]:
pd.DataFrame(X_test_sc).head()

     0         1          2    3
0 -0.2  0.000000   0.350140  0.1
1  0.7  0.000000   7.352941  0.4
2  0.2 -5.602241  -3.151261 -0.4
3 -1.5  0.000000 -23.459384 -1.3
4  0.7 -1.400560   1.050420  0.1

In [55]:
#스케일링이 된 데이터를 원본으로 사용
X_origin = ruscaler.inverse_transform(X_train_sc)

pd.DataFrame(X_origin).head()

        0        1          2       3
0  7.6550  3.70028  42.982913  2.0100
1  6.5950  2.29972  33.038936  2.4675
2  6.1975  1.59944  33.038936  1.4000
3  5.4025  1.24930  -6.736975  1.2475
4  4.7400  3.70028 -76.344818 -0.4300

In [56]:
X_train3.head()

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
125                7.2               3.2                6.0               1.8
128                6.4               2.8                5.6               2.1
134                6.1               2.6                5.6               1.4
89                 5.5               2.5                4.0               1.3
35                 5.0               3.2                1.2               0.2