In [57]:
import pandas as pd

In [58]:
#csv 폴더 안에 tran_1.csv, tran_2.csv 파일을 로드
tran_1=pd.read_csv('../csv/tran_1.csv')
tran_2=pd.read_csv('../csv/tran_2.csv')

In [59]:
tran_1.head(1)

  transaction_id   price         payment_date customer_id
0    T0000000113  210000  2019-02-01 01:36:57    PL563502

In [60]:
tran_2.head(1)

  transaction_id   price         payment_date customer_id
0    T0000005113  295000  2019-06-15 07:20:27    TS169261

In [61]:
tran_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  5000 non-null   str
 1   price           5000 non-null   int64
 2   payment_date    5000 non-null   str
 3   customer_id     5000 non-null   str
dtypes: int64(1), str(3)
memory usage: 156.4 KB

In [62]:
tran_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 1786 entries, 0 to 1785
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  1786 non-null   str
 1   price           1786 non-null   int64
 2   payment_date    1786 non-null   str
 3   customer_id     1786 non-null   str
dtypes: int64(1), str(3)
memory usage: 55.9 KB

In [63]:
#tran_1과 tran_2 데이터를 결합
    #두개의 데이터프레임은 테이블의 구조가 같은 형태
    #단순한 행 결합
    #두개의 데이테프레임이 행결합하면 rows의 개수는 5000+1786=6786
#concat() 함수 이용
#pandas 안에 concat 함수 호출 --> 원본의 데이터라는 개념이 존재 X -> 결과를 저장하려면 새로운 변수에 대입
tran=pd.concat(
    [tran_1,tran_2],axis=0,ignore_index=True
)

In [64]:
tran.info()

<class 'pandas.DataFrame'>
RangeIndex: 6786 entries, 0 to 6785
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  6786 non-null   str
 1   price           6786 non-null   int64
 2   payment_date    6786 non-null   str
 3   customer_id     6786 non-null   str
dtypes: int64(1), str(3)
memory usage: 212.2 KB

In [65]:
# tran_d_1.csv, tran_d_2.csv 파일을 로드
tran_d_1=pd.read_csv('../csv/tran_d_1.csv')
tran_d_2=pd.read_csv('../csv/tran_d_2.csv')

In [66]:
tran_d_1.head(1)

   detail_id transaction_id item_id  quantity
0          0    T0000000113    S005         1

In [67]:
tran_d_2.head(1)

   detail_id transaction_id item_id  quantity
0       5000    T0000004870    S002         3

In [68]:
tran_d_1.info()

<class 'pandas.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       5000 non-null   int64
 1   transaction_id  5000 non-null   str
 2   item_id         5000 non-null   str
 3   quantity        5000 non-null   int64
dtypes: int64(2), str(2)
memory usage: 156.4 KB

In [69]:
tran_d_2.info()

<class 'pandas.DataFrame'>
RangeIndex: 2144 entries, 0 to 2143
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       2144 non-null   int64
 1   transaction_id  2144 non-null   str
 2   item_id         2144 non-null   str
 3   quantity        2144 non-null   int64
dtypes: int64(2), str(2)
memory usage: 67.1 KB

In [70]:
# tran_d_1, tran_d_2 데이터프레임을 단순 행 결합
tran_d=pd.concat(
    [tran_d_1,tran_d_2],axis=0,ignore_index=True
)

In [71]:
tran_d.info()

<class 'pandas.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   detail_id       7144 non-null   int64
 1   transaction_id  7144 non-null   str
 2   item_id         7144 non-null   str
 3   quantity        7144 non-null   int64
dtypes: int64(2), str(2)
memory usage: 223.4 KB

In [72]:
tran.head(1)

  transaction_id   price         payment_date customer_id
0    T0000000113  210000  2019-02-01 01:36:57    PL563502

In [73]:
tran_d.head(1)

   detail_id transaction_id item_id  quantity
0          0    T0000000113    S005         1

In [74]:
tran_d['transaction_id'].value_counts()

transaction_id
T0000000790    4
T0000000231    3
T0000000383    3
T0000000397    3
T0000000513    3
              ..
T0000006894    1
T0000006895    1
T0000006896    1
T0000006897    1
T0000006898    1
Name: count, Length: 6786, dtype: int64

In [75]:
tran['transaction_id'].describe()

count            6786
unique           6786
top       T0000000113
freq                1
Name: transaction_id, dtype: object

In [76]:
#tran과 tran_d 데이터프레임을 결합
#테이블의 구조는 다르게 구성 -> 단순한 행 결합 불가능
#인덱스의 개수가 다르다 -> 6786 // 7144개의 데이터
#두개의 데이터프레임이 공통적으로 가지고 있는 데이터 컬럼은 존재하는가? 
    #transaction_id 컬럼은 공통적으로 가지고 있다 -> 조인 결합 가능
#tran의 인덱스의 수는 6786개
#tran_d의 인덱스의 수는 7144개 
    #두 개의 데이터프레임을 조인결합 했을떄 인덱스의 수느 어떻게 나올 것인가?
    #6876 // 7144 --> how에 따라 다르게 나올 것인가?
transaction=pd.merge(
    tran,tran_d,
    #조건(두개의 데이터프레임이 공통적으로 가지고 있는 컬럼의 이름)
    on = 'transaction_id',
    #결합의 방식은 어떻게 할 것인가?
    how='outer'
)

In [77]:
#총 4개의 데이터파일을 하나의 데이터프레임으로 결합
transaction

,transaction_id,price,payment_date,customer_id,detail_id,item_id,quantity
0,T0000000113,210000,2019-02-01 01:36:57,PL563502,0,S005,1
1,T0000000114,50000,2019-02-01 01:37:23,HD678019,1,S001,1
2,T0000000115,120000,2019-02-01 02:34:19,HD298120,2,S003,1
3,T0000000116,210000,2019-02-01 02:47:23,IK452215,3,S005,1
4,T0000000117,170000,2019-02-01 04:33:46,PL542865,4,S002,2
...,...,...,...,...,...,...,...
7139,T0000006894,180000,2019-07-31 21:20:44,HI400734,7139,S004,1
7140,T0000006895,85000,2019-07-31 21:52:48,AS339451,7140,S002,1
7141,T0000006896,100000,2019-07-31 23:35:25,OA027325,7141,S001,2
7142,T0000006897,85000,2019-07-31 23:39:35,TS624738,7142,S002,1
7143,T0000006898,85000,2019-07-31 23:41:38,AS834214,7143,S002,1

#### 데이터 결합 연습
1. transaction 데이터프레임과 csv 폴더 안에 item_master 파일을 로드하여 2개의 데이터프레임 결합
2. 결합된 데이터에 csv폴더의 customer_master 파일을 로드하여 데이터프레임 결합
3. payment_date 컬럼의 데이터를 시계열 데이터로 변환(to_datetime(Series))

In [78]:
#By Me
item_master=pd.read_csv('../csv/item_master.csv')

In [79]:
item_master.head()

  item_id item_name  item_price
0    S001      PC-A       50000
1    S002      PC-B       85000
2    S003      PC-C      120000
3    S004      PC-D      180000
4    S005      PC-E      210000

In [80]:
tran_item=pd.merge(
    transaction,item_master,on='item_id',how='outer'
)

In [81]:
tran_item.head()

,transaction_id,price,payment_date,customer_id,detail_id,item_id,quantity,item_name,item_price
0,T0000000114,50000,2019-02-01 01:37:23,HD678019,1,S001,1,PC-A,50000
1,T0000000120,50000,2019-02-01 06:22:39,IK624245,7,S001,1,PC-A,50000
2,T0000000123,50000,2019-02-01 09:32:27,OA336650,10,S001,1,PC-A,50000
3,T0000000129,50000,2019-02-01 18:08:59,TS146087,16,S001,1,PC-A,50000
4,T0000000134,150000,2019-02-01 22:08:51,TS701801,21,S001,3,PC-A,50000

In [82]:
customer=pd.read_csv('../csv/customer_master.csv')

In [83]:
customer.head()

,customer_id,name,class,gender,start_date,end_date,campaign_id,is_deleted
0,OA832399,XXXX,C01,F,2015-05-01 00:00:00,NaN,CA1,0
1,PL270116,XXXXX,C01,M,2015-05-01 00:00:00,NaN,CA1,0
2,OA974876,XXXXX,C01,M,2015-05-01 00:00:00,NaN,CA1,0
3,HD024127,XXXXX,C01,F,2015-05-01 00:00:00,NaN,CA1,0
4,HD661448,XXXXX,C03,F,2015-05-01 00:00:00,NaN,CA1,0

In [84]:
tran_cust=pd.merge(
    tran_item,customer, on='customer_id',how='outer'
)

In [85]:
tran_cust.head()

,transaction_id,price,payment_date,customer_id,detail_id,item_id,quantity,item_name,item_price,name,class,gender,start_date,end_date,campaign_id,is_deleted
0,T0000002829,100000.0,2019-04-13 22:38:07,AS002855,2853.0,S001,2.0,PC-A,50000.0,XXXX,C03,F,2016-11-01 00:00:00,NaN,CA1,0.0
1,T0000002774,210000.0,2019-04-12 11:20:10,AS002855,2793.0,S005,1.0,PC-E,210000.0,XXXX,C03,F,2016-11-01 00:00:00,NaN,CA1,0.0
2,NaN,NaN,NaN,AS008805,NaN,NaN,NaN,NaN,NaN,XXXXX,C01,M,2018-06-07 00:00:00,2019-03-31 00:00:00,CA2,1.0
3,T0000006381,50000.0,2019-07-18 08:17:47,AS009013,6600.0,S001,1.0,PC-A,50000.0,XXXXX,C03,M,2017-08-01 00:00:00,2018-04-30 00:00:00,CA2,1.0
4,T0000001976,85000.0,2019-03-22 06:47:38,AS009013,1964.0,S002,1.0,PC-B,85000.0,XXXXX,C03,M,2017-08-01 00:00:00,2018-04-30 00:00:00,CA2,1.0

In [86]:
tran_cust['payment_date']

0       2019-04-13 22:38:07
1       2019-04-12 11:20:10
2                       NaN
3       2019-07-18 08:17:47
4       2019-03-22 06:47:38
               ...
8779    2019-03-10 23:11:09
8780    2019-04-28 03:12:48
8781    2019-05-08 21:58:35
8782    2019-05-26 05:04:27
8783    2019-02-15 05:17:51
Name: payment_date, Length: 8784, dtype: str

In [87]:
pd.to_datetime(tran_cust['payment_date'])

0      2019-04-13 22:38:07
1      2019-04-12 11:20:10
2                      NaT
3      2019-07-18 08:17:47
4      2019-03-22 06:47:38
               ...
8779   2019-03-10 23:11:09
8780   2019-04-28 03:12:48
8781   2019-05-08 21:58:35
8782   2019-05-26 05:04:27
8783   2019-02-15 05:17:51
Name: payment_date, Length: 8784, dtype: datetime64[us]

In [88]:
#By 강사님
item_master=pd.read_csv('../csv/item_master.csv')
customer_master=pd.read_csv('../csv/customer_master.csv')

In [89]:
item_master.head(1)

  item_id item_name  item_price
0    S001      PC-A       50000

In [90]:
customer_master.head(1)

,customer_id,name,class,gender,start_date,end_date,campaign_id,is_deleted
0,OA832399,XXXX,C01,F,2015-05-01 00:00:00,NaN,CA1,0

In [91]:
item_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   item_id     5 non-null      str
 1   item_name   5 non-null      str
 2   item_price  5 non-null      int64
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

In [92]:
customer_master.info()

<class 'pandas.DataFrame'>
RangeIndex: 4192 entries, 0 to 4191
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  4192 non-null   str
 1   name         4192 non-null   str
 2   class        4192 non-null   str
 3   gender       4192 non-null   str
 4   start_date   4192 non-null   str
 5   end_date     1350 non-null   str
 6   campaign_id  4192 non-null   str
 7   is_deleted   4192 non-null   int64
dtypes: int64(1), str(7)
memory usage: 262.1 KB

In [93]:
transaction.info()

<class 'pandas.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  7144 non-null   str
 1   price           7144 non-null   int64
 2   payment_date    7144 non-null   str
 3   customer_id     7144 non-null   str
 4   detail_id       7144 non-null   int64
 5   item_id         7144 non-null   str
 6   quantity        7144 non-null   int64
dtypes: int64(3), str(4)
memory usage: 390.8 KB

In [94]:
#transation, item_master 조인 결합 -> 공통 컬럼은 item_id
df=transaction.merge(
    item_master,
    on='item_id',
    how='inner'
)

In [95]:
df.info()
#item_master에서 결합된 컬럼 item_name, item_price의 결측치가 존재하지 않는다.
#같은 집합 : item_id 기준으로 inner 결합 -> 인첵스 유지 / 결측치 존재 X

<class 'pandas.DataFrame'>
RangeIndex: 7144 entries, 0 to 7143
Data columns (total 9 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  7144 non-null   str
 1   price           7144 non-null   int64
 2   payment_date    7144 non-null   str
 3   customer_id     7144 non-null   str
 4   detail_id       7144 non-null   int64
 5   item_id         7144 non-null   str
 6   quantity        7144 non-null   int64
 7   item_name       7144 non-null   str
 8   item_price      7144 non-null   int64
dtypes: int64(4), str(5)
memory usage: 502.4 KB

In [96]:
#df와 customer_master 조인 결합 -> 조건 customer_id
df=pd.merge(
    df, customer_master,
    on='customer_id',
    how='inner'
)

In [97]:
#시계얄 데이터 patment_date 컬럼을 타입을 변경
#문자를 시계열로 변경(datetime.strptime()/to_datetime())
pd.to_datetime(df['payment_date'])

0      2019-02-01 01:36:57
1      2019-02-01 01:37:23
2      2019-02-01 02:34:19
3      2019-02-01 02:47:23
4      2019-02-01 04:33:46
               ...
6064   2019-07-31 20:28:20
6065   2019-07-31 21:17:39
6066   2019-07-31 21:52:48
6067   2019-07-31 23:35:25
6068   2019-07-31 23:41:38
Name: payment_date, Length: 6069, dtype: datetime64[us]

In [98]:
#datetime 라이브러리의 strptime()을 이용하여 데이터 타입 변환
from datetime import datetime

In [99]:
df['payment_date'][0]

'2019-02-01 01:36:57'

In [100]:
#datetime안에 strptime() 함수는 to_datetime()과는 다르게 Series형태 변환이 불가능
# datetime.strptime(df['payment_date'][0],'%Y-%m-%d %H:%M:%S')
#Series 데이터에서 value들을 하나씩 뽑아서 함수에 넣는다. map()
df['payment_date'].map(
    #x에 대입되는 데이터는 문자
    lambda x : datetime.strptime(x,'%Y-%m-%d %H:%M:%S')
)

0      2019-02-01 01:36:57
1      2019-02-01 01:37:23
2      2019-02-01 02:34:19
3      2019-02-01 02:47:23
4      2019-02-01 04:33:46
               ...
6064   2019-07-31 20:28:20
6065   2019-07-31 21:17:39
6066   2019-07-31 21:52:48
6067   2019-07-31 23:35:25
6068   2019-07-31 23:41:38
Name: payment_date, Length: 6069, dtype: datetime64[us]

In [101]:
#Series 데이터에서 문자열 함수를 사용하기 위해
    #1.반복문 사용
    #2.map()+lambda
    #3.문자열 함수를 사용할 수 있도록 pandas에서 제공한 Series.str (String Method)
#Series에서는 시계열 함수를 사용할 수 있도록 문자열과 같이 DatetimeMethods 변환이 존재
# Series.str --> 해당 데이터셋이 시계열로 시계열 함수

In [102]:
df['payment_date']=pd.to_datetime(df['payment_date'])

In [103]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6069 entries, 0 to 6068
Data columns (total 16 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  6069 non-null   str
 1   price           6069 non-null   int64
 2   payment_date    6069 non-null   datetime64[us]
 3   customer_id     6069 non-null   str
 4   detail_id       6069 non-null   int64
 5   item_id         6069 non-null   str
 6   quantity        6069 non-null   int64
 7   item_name       6069 non-null   str
 8   item_price      6069 non-null   int64
 9   name            6069 non-null   str
 10  class           6069 non-null   str
 11  gender          6069 non-null   str
 12  start_date      6069 non-null   str
 13  end_date        1978 non-null   str
 14  campaign_id     6069 non-null   str
 15  is_deleted      6069 non-null   int64
dtypes: datetime64[us](1), int64(5), str(10)
memory usage: 758.8 KB

In [104]:
#요일별 판매가 된 제품들의 총 판매 개수들의 함계가 어떻게 되는가?
#요일이라는 새로운 변수를 생성 -> 시계열에서 요일만 따로 추출(strftime(%A | %a | %w))
df['요일']=df['payment_date'].dt.strftime('%A')
#strftime() : 0(일),...

In [105]:
df['payment_date'].dt.weekday
#weekday : 0(월),...

0       4
1       4
2       4
3       4
4       4
       ..
6064    2
6065    2
6066    2
6067    2
6068    2
Name: payment_date, Length: 6069, dtype: int32

In [106]:
df.head(1)

,transaction_id,price,payment_date,customer_id,detail_id,item_id,quantity,item_name,item_price,name,class,gender,start_date,end_date,campaign_id,is_deleted,요일
0,T0000000113,210000,2019-02-01 01:36:57,PL563502,0,S005,1,PC-E,210000,XX,C01,M,2018-07-01 00:00:00,NaN,CA1,0,Friday

In [107]:
#요일, item_id를 기준으로 그룹화 -> quantity의 합산
df[['요일','item_id','quantity']].groupby(['요일','item_id']).sum()

                   quantity
요일        item_id
Friday    S001          406
          S002          250
          S003          140
          S004          105
          S005          225
Monday    S001          363
          S002          201
          S003          132
          S004           97
          S005          207
Saturday  S001          367
          S002          182
          S003          141
          S004          102
          S005          231
Sunday    S001          390
          S002          236
          S003          121
          S004          121
          S005          210
Thursday  S001          334
          S002          206
          S003          128
          S004          103
          S005          227
Tuesday   S001          336
          S002          227
          S003          121
          S004          107
          S005          212
Wednesday S001          382
          S002          216
          S003           98
          S004          122
          S005          241

In [112]:
#transaction데이터에서 customer_id와 customer_master 데이터에서 customer_id값들이 다른가?

list_1=transaction['customer_id'].unique()

In [113]:
list_2=customer_master['customer_id'].unique()

In [ ]:
#두개의 리스트에서 서로 다른 값이 다른 데이터는 어떻게 되는가?
new_list=[]

for customer in list_1:
    if customer  not in list_2:
        #고객의 ID가 list_2에 존재하지 않는다면
        new_list.append(customer)

new_list

['GD029189',
 'PL674172',
 'HI364290',
 'AS866028',
 'TS301045',
 'OA567188',
 'GD011312',
 'GD960920',
 'TS508850',
 'OA861572',
 'GD246033',
 'PL470875',
 'GD883278',
 'IK397678',
 'HI988473',
 'HI978950',
 'GD021809',
 'GD288833',
 'PL807633',
 'HI780705',
 'IK345440',
 'GD727041',
 'IK844273',
 'OA222039',
 'GD804496',
 'TS771339',
 'PL896084',
 'IK943660',
 'GD638254',
 'PL598638',
 'AS369586',
 'IK466573',
 'GD956496',
 'HI791416',
 'OA911257',
 'HD622485',
 'IK423708',
 'OA142331',
 'GD098828',
 'AS230629',
 'TS855513',
 'TS372874',
 'HD827887',
 'TS179639',
 'AS921368',
 'HI303118',
 'TS808488',
 'HI654320',
 'HD430217',
 'OA283746',
 'TS962550',
 'PL600990',
 'TS451704',
 'AS895302',
 'HD673446',
 'TS722923',
 'OA228291',
 'TS674550',
 'HI183093',
 'HI231462',
 'AS112674',
 'PL538095',
 'IK627931',
 'PL563001',
 'HI247905',
 'PL243765',
 'IK013691',
 'GD850851',
 'TS825520',
 'IK289800',
 'HI733623',
 'GD378835',
 'HI487042',
 'PL484153',
 'TS645665',
 'TS667446',
 'TS985967',
 'IK590154',
 'HI026312',
 'OA760273',
 'OA186884',
 'AS047815',
 'GD150760',
 'PL471011',
 'OA348005',
 'HD108205',
 'OA275501',
 'IK183913',
 'HI561542',
 'HI407816',
 'OA378430',
 'HI754267',
 'PL070030',
 'TS120796',
 'PL212792',
 'AS780890',
 'GD902176',
 'HI400734',
 'IK330019',
 'HD628998',
 'AS882678',
 'OA653324',
 'HI400606',
 'PL634625',
 'HI318091',
 'HI898602',
 'PL301503',
 'HD411688',
 'PL195594',
 'HI626820',
 'HI358653',
 'PL265818',
 'HD123842',
 'AS979183',
 'GD968190',
 'HI672548',
 'HD838779',
 'IK609024',
 'OA118869',
 'TS851428',
 'GD455127',
 'HD962462',
 'AS375220',
 'TS248015',
 'TS425666',
 'GD727286',
 'AS278780',
 'HD461880',
 'OA019548',
 'HI690734',
 'PL681254',
 'OA144055',
 'HD558047',
 'PL591140',
 'PL534834',
 'GD643063',
 'OA195904',
 'HI944908',
 'AS352269',
 'PL980829',
 'IK453239',
 'IK419862',
 'TS474137',
 'GD185040',
 'PL550068',
 'HD761271',
 'TS568764',
 'HI355281',
 'HD938156',
 'GD993938',
 'OA490350',
 'HD912521',
 'PL229747',
 'HD724900',
 'PL486566',
 'IK547632',
 'TS822034',
 'TS683058',
 'PL252397',
 'TS580222',
 'TS624738',
 'AS605111',
 'OA336098',
 'OA959426',
 'HI262793',
 'OA256309',
 'AS644996',
 'PL399121',
 'IK993568',
 'HD668790',
 'TS060125',
 'GD094299',
 'IK818641',
 'IK110954',
 'GD265984',
 'PL102045',
 'HI090280',
 'OA181249',
 'TS257398',
 'AS834628',
 'GD150899',
 'TS355204',
 'PL820272',
 'AS125481',
 'IK476630',
 'TS064786',
 'AS120487',
 'TS045314',
 'AS793257',
 'TS340142',
 'AS033208',
 'HI535598',
 'AS772027',
 'TS898614',
 'PL160503',
 'AS355098',
 'PL167583',
 'GD688950',
 'IK952589',
 'HD992446',
 'HI040881',
 'GD083109',
 'GD034021',
 'OA214023',
 'HD502728',
 'GD308876',
 'OA441791',
 'OA301378',
 'GD154170',
 'OA518938',
 'TS752438',
 'TS260832',
 'IK071733',
 'HI025685',
 'OA765757',
 'AS129796',
 'TS506913',
 'HI078880',
 'OA506453',
 'IK419506',
 'AS568755',
 'AS310768',
 'OA473384',
 'GD843122',
 'HI008566',
 'TS641433',
 'AS892734',
 'AS033898',
 'PL585092',
 'IK963761',
 'OA829464',
 'GD990639',
 'PL447530',
 'PL901816',
 'IK759414',
 'HI510103',
 'TS733060',
 'GD191213',
 'IK163405',
 'HD049383',
 'IK453679',
 'IK299592',
 'IK855920',
 'PL212885',
 'IK424256',
 'TS533240',
 'TS830677',
 'AS639935',
 'IK544197',
 'AS168089',
 'IK153469',
 'HD639099',
 'IK725315',
 'TS562162',
 'HI327600',
 'IK015043',
 'IK597697',
 'PL990239',
 'IK121456',
 'IK099799',
 'TS117978',
 'OA086657',
 'HD794402',
 'HI322241',
 'TS414273',
 'OA373649',
 'PL958111',
 'OA419499',
 'HD214093',
 'PL263245',
 'AS463573',
 'AS727393',
 'AS648839',
 'GD606287',
 'GD854836',
 'OA288436',
 'TS945876',
 'PL690532',
 'HD523310',
 'OA913755',
 'OA310931',
 'AS541179',
 'HI897445',
 'PL613382',
 'GD818751',
 'GD569284',
 'TS290297',
 'OA770389',
 'IK431399',
 'IK866166',
 'TS567737',
 'IK074758',
 'GD124507',
 'AS303022',
 'OA283278',
 'HD247559',
 'OA139077',
 'PL368937',
 'HD940282',
 'IK253267',
 'HI414861',
 'HI995754',
 'IK426871',
 'TS721555',
 'PL557508',
 'HD826841',
 'TS724169',
 'HD184889',
 'PL204290',
 'PL365264',
 'PL170857',
 'AS984476',
 'HI523163',
 'GD132214',
 'IK224764',
 'TS342077',
 'HD794427',
 'GD465345',
 'PL086937',
 'HI444425',
 'GD238109',
 'IK431694',
 'IK504560',
 'HD656297',
 'AS548391',
 'IK487798',
 'GD542439',
 'AS325900',
 'AS711277',
 'HI174776',
 'PL570346',
 'TS806450',
 'AS459936',
 'HD001989',
 'TS215112',
 'HD237842',
 'OA603276',
 'IK349052',
 'AS346715',
 'GD071442',
 'TS875763',
 'PL498703',
 'OA406727',
 'HD502657',
 'PL560462',
 'HI345781',
 'HI715559',
 'GD942457',
 'OA314234',
 'PL697195',
 'HD735632',
 'HD044650',
 'TS291302',
 'OA514276',
 'PL853016',
 'OA254984',
 'HD444151',
 'HD500570',
 'TS267517',
 'PL344424',
 'TS399940',
 'OA168067',
 'HD797921',
 'PL287707',
 'AS192134',
 'AS215309',
 'HI748457',
 'OA497830',
 'IK163905',
 'TS753499',
 'GD192169',
 'IK951311',
 'PL411913',
 'HI139822',
 'HI265546',
 'GD026761',
 'OA237366',
 'OA828946',
 'AS111667',
 'PL870239',
 'TS717899',
 'OA770978',
 'IK299335',
 'HD544869',
 'HI601096',
 'HD438863',
 'PL776592',
 'PL083738',
 'OA012423',
 'HI926999',
 'AS366153',
 'HI295053',
 'OA352170',
 'TS563606',
 'OA093559',
 'OA184387',
 'HI648050',
 'AS886949',
 'OA229900',
 'IK631512',
 'AS123190',
 'HI616611',
 'AS369861',
 'PL804383',
 'OA681007',
 'TS716875',
 'OA838720',
 'HD648882',
 'TS981486',
 'IK420707',
 'HD078028',
 'HD685797',
 'TS429065',
 'TS860951',
 'OA639613',
 'PL866564',
 'IK529029',
 'TS934599',
 'PL049894',
 'IK863423',
 'PL466152',
 'HD660527',
 'PL511118',
 'TS012855',
 'TS712179',
 'OA096648',
 'TS418116',
 'IK432395',
 'GD695904',
 'OA717373',
 'GD569028',
 'GD653232',
 'TS909340',
 'HI422196',
 'GD936161',
 'HI678851',
 'TS069597',
 'AS754176',
 'HI844603',
 'HI248527',
 'GD399384',
 'TS972650',
 'IK164996',
 'PL509689',
 'PL660484',
 'IK777110',
 'HI900832',
 'PL852001',
 'OA481390',
 'HD939520',
 'HD755168',
 'TS897204',
 'GD550784',
 'HD434419',
 'TS005920',
 'AS228133',
 'IK911976',
 'AS034137',
 'HI009305',
 'TS344882',
 'PL361201',
 'AS905186',
 'HD880785',
 'IK311957',
 'GD905295',
 'PL482487']

In [116]:
[customer for customer in list_1 if customer not in list_2]

['GD029189',
 'PL674172',
 'HI364290',
 'AS866028',
 'TS301045',
 'OA567188',
 'GD011312',
 'GD960920',
 'TS508850',
 'OA861572',
 'GD246033',
 'PL470875',
 'GD883278',
 'IK397678',
 'HI988473',
 'HI978950',
 'GD021809',
 'GD288833',
 'PL807633',
 'HI780705',
 'IK345440',
 'GD727041',
 'IK844273',
 'OA222039',
 'GD804496',
 'TS771339',
 'PL896084',
 'IK943660',
 'GD638254',
 'PL598638',
 'AS369586',
 'IK466573',
 'GD956496',
 'HI791416',
 'OA911257',
 'HD622485',
 'IK423708',
 'OA142331',
 'GD098828',
 'AS230629',
 'TS855513',
 'TS372874',
 'HD827887',
 'TS179639',
 'AS921368',
 'HI303118',
 'TS808488',
 'HI654320',
 'HD430217',
 'OA283746',
 'TS962550',
 'PL600990',
 'TS451704',
 'AS895302',
 'HD673446',
 'TS722923',
 'OA228291',
 'TS674550',
 'HI183093',
 'HI231462',
 'AS112674',
 'PL538095',
 'IK627931',
 'PL563001',
 'HI247905',
 'PL243765',
 'IK013691',
 'GD850851',
 'TS825520',
 'IK289800',
 'HI733623',
 'GD378835',
 'HI487042',
 'PL484153',
 'TS645665',
 'TS667446',
 'TS985967',
 'IK590154',
 'HI026312',
 'OA760273',
 'OA186884',
 'AS047815',
 'GD150760',
 'PL471011',
 'OA348005',
 'HD108205',
 'OA275501',
 'IK183913',
 'HI561542',
 'HI407816',
 'OA378430',
 'HI754267',
 'PL070030',
 'TS120796',
 'PL212792',
 'AS780890',
 'GD902176',
 'HI400734',
 'IK330019',
 'HD628998',
 'AS882678',
 'OA653324',
 'HI400606',
 'PL634625',
 'HI318091',
 'HI898602',
 'PL301503',
 'HD411688',
 'PL195594',
 'HI626820',
 'HI358653',
 'PL265818',
 'HD123842',
 'AS979183',
 'GD968190',
 'HI672548',
 'HD838779',
 'IK609024',
 'OA118869',
 'TS851428',
 'GD455127',
 'HD962462',
 'AS375220',
 'TS248015',
 'TS425666',
 'GD727286',
 'AS278780',
 'HD461880',
 'OA019548',
 'HI690734',
 'PL681254',
 'OA144055',
 'HD558047',
 'PL591140',
 'PL534834',
 'GD643063',
 'OA195904',
 'HI944908',
 'AS352269',
 'PL980829',
 'IK453239',
 'IK419862',
 'TS474137',
 'GD185040',
 'PL550068',
 'HD761271',
 'TS568764',
 'HI355281',
 'HD938156',
 'GD993938',
 'OA490350',
 'HD912521',
 'PL229747',
 'HD724900',
 'PL486566',
 'IK547632',
 'TS822034',
 'TS683058',
 'PL252397',
 'TS580222',
 'TS624738',
 'AS605111',
 'OA336098',
 'OA959426',
 'HI262793',
 'OA256309',
 'AS644996',
 'PL399121',
 'IK993568',
 'HD668790',
 'TS060125',
 'GD094299',
 'IK818641',
 'IK110954',
 'GD265984',
 'PL102045',
 'HI090280',
 'OA181249',
 'TS257398',
 'AS834628',
 'GD150899',
 'TS355204',
 'PL820272',
 'AS125481',
 'IK476630',
 'TS064786',
 'AS120487',
 'TS045314',
 'AS793257',
 'TS340142',
 'AS033208',
 'HI535598',
 'AS772027',
 'TS898614',
 'PL160503',
 'AS355098',
 'PL167583',
 'GD688950',
 'IK952589',
 'HD992446',
 'HI040881',
 'GD083109',
 'GD034021',
 'OA214023',
 'HD502728',
 'GD308876',
 'OA441791',
 'OA301378',
 'GD154170',
 'OA518938',
 'TS752438',
 'TS260832',
 'IK071733',
 'HI025685',
 'OA765757',
 'AS129796',
 'TS506913',
 'HI078880',
 'OA506453',
 'IK419506',
 'AS568755',
 'AS310768',
 'OA473384',
 'GD843122',
 'HI008566',
 'TS641433',
 'AS892734',
 'AS033898',
 'PL585092',
 'IK963761',
 'OA829464',
 'GD990639',
 'PL447530',
 'PL901816',
 'IK759414',
 'HI510103',
 'TS733060',
 'GD191213',
 'IK163405',
 'HD049383',
 'IK453679',
 'IK299592',
 'IK855920',
 'PL212885',
 'IK424256',
 'TS533240',
 'TS830677',
 'AS639935',
 'IK544197',
 'AS168089',
 'IK153469',
 'HD639099',
 'IK725315',
 'TS562162',
 'HI327600',
 'IK015043',
 'IK597697',
 'PL990239',
 'IK121456',
 'IK099799',
 'TS117978',
 'OA086657',
 'HD794402',
 'HI322241',
 'TS414273',
 'OA373649',
 'PL958111',
 'OA419499',
 'HD214093',
 'PL263245',
 'AS463573',
 'AS727393',
 'AS648839',
 'GD606287',
 'GD854836',
 'OA288436',
 'TS945876',
 'PL690532',
 'HD523310',
 'OA913755',
 'OA310931',
 'AS541179',
 'HI897445',
 'PL613382',
 'GD818751',
 'GD569284',
 'TS290297',
 'OA770389',
 'IK431399',
 'IK866166',
 'TS567737',
 'IK074758',
 'GD124507',
 'AS303022',
 'OA283278',
 'HD247559',
 'OA139077',
 'PL368937',
 'HD940282',
 'IK253267',
 'HI414861',
 'HI995754',
 'IK426871',
 'TS721555',
 'PL557508',
 'HD826841',
 'TS724169',
 'HD184889',
 'PL204290',
 'PL365264',
 'PL170857',
 'AS984476',
 'HI523163',
 'GD132214',
 'IK224764',
 'TS342077',
 'HD794427',
 'GD465345',
 'PL086937',
 'HI444425',
 'GD238109',
 'IK431694',
 'IK504560',
 'HD656297',
 'AS548391',
 'IK487798',
 'GD542439',
 'AS325900',
 'AS711277',
 'HI174776',
 'PL570346',
 'TS806450',
 'AS459936',
 'HD001989',
 'TS215112',
 'HD237842',
 'OA603276',
 'IK349052',
 'AS346715',
 'GD071442',
 'TS875763',
 'PL498703',
 'OA406727',
 'HD502657',
 'PL560462',
 'HI345781',
 'HI715559',
 'GD942457',
 'OA314234',
 'PL697195',
 'HD735632',
 'HD044650',
 'TS291302',
 'OA514276',
 'PL853016',
 'OA254984',
 'HD444151',
 'HD500570',
 'TS267517',
 'PL344424',
 'TS399940',
 'OA168067',
 'HD797921',
 'PL287707',
 'AS192134',
 'AS215309',
 'HI748457',
 'OA497830',
 'IK163905',
 'TS753499',
 'GD192169',
 'IK951311',
 'PL411913',
 'HI139822',
 'HI265546',
 'GD026761',
 'OA237366',
 'OA828946',
 'AS111667',
 'PL870239',
 'TS717899',
 'OA770978',
 'IK299335',
 'HD544869',
 'HI601096',
 'HD438863',
 'PL776592',
 'PL083738',
 'OA012423',
 'HI926999',
 'AS366153',
 'HI295053',
 'OA352170',
 'TS563606',
 'OA093559',
 'OA184387',
 'HI648050',
 'AS886949',
 'OA229900',
 'IK631512',
 'AS123190',
 'HI616611',
 'AS369861',
 'PL804383',
 'OA681007',
 'TS716875',
 'OA838720',
 'HD648882',
 'TS981486',
 'IK420707',
 'HD078028',
 'HD685797',
 'TS429065',
 'TS860951',
 'OA639613',
 'PL866564',
 'IK529029',
 'TS934599',
 'PL049894',
 'IK863423',
 'PL466152',
 'HD660527',
 'PL511118',
 'TS012855',
 'TS712179',
 'OA096648',
 'TS418116',
 'IK432395',
 'GD695904',
 'OA717373',
 'GD569028',
 'GD653232',
 'TS909340',
 'HI422196',
 'GD936161',
 'HI678851',
 'TS069597',
 'AS754176',
 'HI844603',
 'HI248527',
 'GD399384',
 'TS972650',
 'IK164996',
 'PL509689',
 'PL660484',
 'IK777110',
 'HI900832',
 'PL852001',
 'OA481390',
 'HD939520',
 'HD755168',
 'TS897204',
 'GD550784',
 'HD434419',
 'TS005920',
 'AS228133',
 'IK911976',
 'AS034137',
 'HI009305',
 'TS344882',
 'PL361201',
 'AS905186',
 'HD880785',
 'IK311957',
 'GD905295',
 'PL482487']

In [118]:
#집합 데이터 타입 : { } | set() 묶어서 데이터 생성
#집합 : 중복데이터가 존재하지 않음
set(transaction['customer_id']) - set(customer_master['customer_id'])

{'AS033208',
 'AS033898',
 'AS034137',
 'AS047815',
 'AS111667',
 'AS112674',
 'AS120487',
 'AS123190',
 'AS125481',
 'AS129796',
 'AS168089',
 'AS192134',
 'AS215309',
 'AS228133',
 'AS230629',
 'AS278780',
 'AS303022',
 'AS310768',
 'AS325900',
 'AS346715',
 'AS352269',
 'AS355098',
 'AS366153',
 'AS369586',
 'AS369861',
 'AS375220',
 'AS459936',
 'AS463573',
 'AS541179',
 'AS548391',
 'AS568755',
 'AS605111',
 'AS639935',
 'AS644996',
 'AS648839',
 'AS711277',
 'AS727393',
 'AS754176',
 'AS772027',
 'AS780890',
 'AS793257',
 'AS834628',
 'AS866028',
 'AS882678',
 'AS886949',
 'AS892734',
 'AS895302',
 'AS905186',
 'AS921368',
 'AS979183',
 'AS984476',
 'GD011312',
 'GD021809',
 'GD026761',
 'GD029189',
 'GD034021',
 'GD071442',
 'GD083109',
 'GD094299',
 'GD098828',
 'GD124507',
 'GD132214',
 'GD150760',
 'GD150899',
 'GD154170',
 'GD185040',
 'GD191213',
 'GD192169',
 'GD238109',
 'GD246033',
 'GD265984',
 'GD288833',
 'GD308876',
 'GD378835',
 'GD399384',
 'GD455127',
 'GD465345',
 'GD542439',
 'GD550784',
 'GD569028',
 'GD569284',
 'GD606287',
 'GD638254',
 'GD643063',
 'GD653232',
 'GD688950',
 'GD695904',
 'GD727041',
 'GD727286',
 'GD804496',
 'GD818751',
 'GD843122',
 'GD850851',
 'GD854836',
 'GD883278',
 'GD902176',
 'GD905295',
 'GD936161',
 'GD942457',
 'GD956496',
 'GD960920',
 'GD968190',
 'GD990639',
 'GD993938',
 'HD001989',
 'HD044650',
 'HD049383',
 'HD078028',
 'HD108205',
 'HD123842',
 'HD184889',
 'HD214093',
 'HD237842',
 'HD247559',
 'HD411688',
 'HD430217',
 'HD434419',
 'HD438863',
 'HD444151',
 'HD461880',
 'HD500570',
 'HD502657',
 'HD502728',
 'HD523310',
 'HD544869',
 'HD558047',
 'HD622485',
 'HD628998',
 'HD639099',
 'HD648882',
 'HD656297',
 'HD660527',
 'HD668790',
 'HD673446',
 'HD685797',
 'HD724900',
 'HD735632',
 'HD755168',
 'HD761271',
 'HD794402',
 'HD794427',
 'HD797921',
 'HD826841',
 'HD827887',
 'HD838779',
 'HD880785',
 'HD912521',
 'HD938156',
 'HD939520',
 'HD940282',
 'HD962462',
 'HD992446',
 'HI008566',
 'HI009305',
 'HI025685',
 'HI026312',
 'HI040881',
 'HI078880',
 'HI090280',
 'HI139822',
 'HI174776',
 'HI183093',
 'HI231462',
 'HI247905',
 'HI248527',
 'HI262793',
 'HI265546',
 'HI295053',
 'HI303118',
 'HI318091',
 'HI322241',
 'HI327600',
 'HI345781',
 'HI355281',
 'HI358653',
 'HI364290',
 'HI400606',
 'HI400734',
 'HI407816',
 'HI414861',
 'HI422196',
 'HI444425',
 'HI487042',
 'HI510103',
 'HI523163',
 'HI535598',
 'HI561542',
 'HI601096',
 'HI616611',
 'HI626820',
 'HI648050',
 'HI654320',
 'HI672548',
 'HI678851',
 'HI690734',
 'HI715559',
 'HI733623',
 'HI748457',
 'HI754267',
 'HI780705',
 'HI791416',
 'HI844603',
 'HI897445',
 'HI898602',
 'HI900832',
 'HI926999',
 'HI944908',
 'HI978950',
 'HI988473',
 'HI995754',
 'IK013691',
 'IK015043',
 'IK071733',
 'IK074758',
 'IK099799',
 'IK110954',
 'IK121456',
 'IK153469',
 'IK163405',
 'IK163905',
 'IK164996',
 'IK183913',
 'IK224764',
 'IK253267',
 'IK289800',
 'IK299335',
 'IK299592',
 'IK311957',
 'IK330019',
 'IK345440',
 'IK349052',
 'IK397678',
 'IK419506',
 'IK419862',
 'IK420707',
 'IK423708',
 'IK424256',
 'IK426871',
 'IK431399',
 'IK431694',
 'IK432395',
 'IK453239',
 'IK453679',
 'IK466573',
 'IK476630',
 'IK487798',
 'IK504560',
 'IK529029',
 'IK544197',
 'IK547632',
 'IK590154',
 'IK597697',
 'IK609024',
 'IK627931',
 'IK631512',
 'IK725315',
 'IK759414',
 'IK777110',
 'IK818641',
 'IK844273',
 'IK855920',
 'IK863423',
 'IK866166',
 'IK911976',
 'IK943660',
 'IK951311',
 'IK952589',
 'IK963761',
 'IK993568',
 'OA012423',
 'OA019548',
 'OA086657',
 'OA093559',
 'OA096648',
 'OA118869',
 'OA139077',
 'OA142331',
 'OA144055',
 'OA168067',
 'OA181249',
 'OA184387',
 'OA186884',
 'OA195904',
 'OA214023',
 'OA222039',
 'OA228291',
 'OA229900',
 'OA237366',
 'OA254984',
 'OA256309',
 'OA275501',
 'OA283278',
 'OA283746',
 'OA288436',
 'OA301378',
 'OA310931',
 'OA314234',
 'OA336098',
 'OA348005',
 'OA352170',
 'OA373649',
 'OA378430',
 'OA406727',
 'OA419499',
 'OA441791',
 'OA473384',
 'OA481390',
 'OA490350',
 'OA497830',
 'OA506453',
 'OA514276',
 'OA518938',
 'OA567188',
 'OA603276',
 'OA639613',
 'OA653324',
 'OA681007',
 'OA717373',
 'OA760273',
 'OA765757',
 'OA770389',
 'OA770978',
 'OA828946',
 'OA829464',
 'OA838720',
 'OA861572',
 'OA911257',
 'OA913755',
 'OA959426',
 'PL049894',
 'PL070030',
 'PL083738',
 'PL086937',
 'PL102045',
 'PL160503',
 'PL167583',
 'PL170857',
 'PL195594',
 'PL204290',
 'PL212792',
 'PL212885',
 'PL229747',
 'PL243765',
 'PL252397',
 'PL263245',
 'PL265818',
 'PL287707',
 'PL301503',
 'PL344424',
 'PL361201',
 'PL365264',
 'PL368937',
 'PL399121',
 'PL411913',
 'PL447530',
 'PL466152',
 'PL470875',
 'PL471011',
 'PL482487',
 'PL484153',
 'PL486566',
 'PL498703',
 'PL509689',
 'PL511118',
 'PL534834',
 'PL538095',
 'PL550068',
 'PL557508',
 'PL560462',
 'PL563001',
 'PL570346',
 'PL585092',
 'PL591140',
 'PL598638',
 'PL600990',
 'PL613382',
 'PL634625',
 'PL660484',
 'PL674172',
 'PL681254',
 'PL690532',
 'PL697195',
 'PL776592',
 'PL804383',
 'PL807633',
 'PL820272',
 'PL852001',
 'PL853016',
 'PL866564',
 'PL870239',
 'PL896084',
 'PL901816',
 'PL958111',
 'PL980829',
 'PL990239',
 'TS005920',
 'TS012855',
 'TS045314',
 'TS060125',
 'TS064786',
 'TS069597',
 'TS117978',
 'TS120796',
 'TS179639',
 'TS215112',
 'TS248015',
 'TS257398',
 'TS260832',
 'TS267517',
 'TS290297',
 'TS291302',
 'TS301045',
 'TS340142',
 'TS342077',
 'TS344882',
 'TS355204',
 'TS372874',
 'TS399940',
 'TS414273',
 'TS418116',
 'TS425666',
 'TS429065',
 'TS451704',
 'TS474137',
 'TS506913',
 'TS508850',
 'TS533240',
 'TS562162',
 'TS563606',
 'TS567737',
 'TS568764',
 'TS580222',
 'TS624738',
 'TS641433',
 'TS645665',
 'TS667446',
 'TS674550',
 'TS683058',
 'TS712179',
 'TS716875',
 'TS717899',
 'TS721555',
 'TS722923',
 'TS724169',
 'TS733060',
 'TS752438',
 'TS753499',
 'TS771339',
 'TS806450',
 'TS808488',
 'TS822034',
 'TS825520',
 'TS830677',
 'TS851428',
 'TS855513',
 'TS860951',
 'TS875763',
 'TS897204',
 'TS898614',
 'TS909340',
 'TS934599',
 'TS945876',
 'TS962550',
 'TS972650',
 'TS981486',
 'TS985967'}