### 특정 경로에 있는 파일의 목록을 확인
1. 일반적으로 경로를 설정하고 파일의 이름을 지정하는 방법
    - 상대 경로
    - 절대 경로
2. 특정 경로에 존재하는 파일의 목록을 확인해서 read_xxx() 함수를 이용
    - os 라이브러리
    - glob 라이브러리 + os 라이브러리
3. 파일의 목록을 가지고 왔다면 반복문을 이용해서 데이터들을 로드
    - 각각의 변수에 데이터를 대입
        - 조인 결합을 하기 위해 우선 각각 변수에 대입
    - 하나의 데이터프레임으로 결합하여 변수에 저장
        - 같은 구조의 데이터들을 로드하여 로드하는 경우 하나의 데이터프레임으로 결함( 단순 행 결합 )

In [1]:
#라이브러리 로드
import os
from glob import glob
import pandas as pd

In [2]:
#os 라이브러리를 이용하여 파일의 목록을 로드
#cmd(터미널)의 명령어를 함수화
#dir --> 현제 경로에서 파일의 목록을 보여주는 명령어
#python에서 목록들을 볼 수 있는 데이터의 형태는??? list
#listdir(경로) 함수가 존재
os.listdir('../csv')

['2014.csv',
 '2017',
 '2017_expense_list.csv',
 '2017_expense_list.xlsx',
 '2018',
 '2019',
 '2020',
 '2021',
 '2022',
 '2022년 06월 교통카드통계자료.xls',
 'AAPL.csv',
 'AMZN.csv',
 'boston.csv',
 'california.csv',
 'campaign_master.csv',
 'card',
 'class_master.csv',
 'corona.csv',
 'csv_exam.csv',
 'customer_master.csv',
 'dept.csv',
 'drinks.csv',
 'emp.csv',
 'example.csv',
 'GM.csv',
 'iris.csv',
 'item_master.csv',
 'Koweps_Codebook.xlsx',
 'MSFT.csv',
 'num_1',
 'num_2',
 'num_3',
 'Sales Records.csv',
 'Superstore KR - VizLab 2022.xlsx',
 'test',
 'tran_1.csv',
 'tran_2.csv',
 'tran_d_1.csv',
 'tran_d_2.csv',
 'uriage.csv',
 'use_log.csv',
 'USM.csv',
 '주민등록.csv',
 '태블로']

In [3]:
#csv 폴더안에 2017 폴더의 파일 목록을 확인
os.listdir('../csv/2017/')

['201701_expense_list.csv',
 '201702_expense_list.csv',
 '201703_expense_list.csv',
 '201704_expense_list.csv',
 '201705_expense_list.csv',
 '201706_expense_list.csv',
 '201707_expense_list.csv',
 '201708_expense_list.csv',
 '201709_expense_list.csv',
 '201710_expense_list.csv',
 '201711_expense_list.csv',
 '201712_expense_list.csv']

In [4]:
file_path='../csv/2017/'
file_list=os.listdir(file_path)

for file_name in file_list:
    # print(file_path + file_name)
    df=pd.read_csv(file_path + file_name)
    #12번 반복
    #df=2017년 1월 대입
    #df=2017년 2월 대입 -> 2017년 1월 데이터 제거
    #...
    #df=2017년 12월 대입 -> 2017년 11월 데이터 제거
    #df는 2017년 12월 데이터만 존재
    #반복 실행할때마다 df가 아닌 각각 새로운 변수에 대입
df.head(2)

,nid,title,url,dept_nm_lvl_1,dept_nm_lvl_2,dept_nm_lvl_3,dept_nm_lvl_4,dept_nm_lvl_5,exec_yr,exec_month,expense_budget,expense_execution,category,dept_nm_full,exec_dt,exec_loc,exec_purpose,target_nm,payment_method,exec_amount
0,14356805,2017년 12월 서울시본청_행정국_인사과 업무추진비 내역,http://opengov.seoul.go.kr/public/14356805,서울시본청,행정국,인사과,NaN,NaN,2017,12,NaN,NaN,NaN,행정국 인사과,2017-12-28 22:44,김앤장 (중구 무교로 6),정년명예퇴임식 개선사항 검토를 위한 간담회비 지급,인사기획팀장 등 12명,카드,300000
1,14356805,2017년 12월 서울시본청_행정국_인사과 업무추진비 내역,http://opengov.seoul.go.kr/public/14356805,서울시본청,행정국,인사과,NaN,NaN,2017,12,NaN,NaN,NaN,행정국 인사과,2017-12-28 15:48,황금정 (종로구 당주동1),퇴임식 행사 진행순서 논의 등을 위한 간담회비 지급,성과관리팀장 등 13명,카드,380000

In [5]:
#위 코드의 문제 해결
    #1. 반복실행하면서 다른 전역 변수룰 생성 -> globals 사용
    #2. file_path에 만지막에 '/'가 들어가지 않으면 문제 발생 (/추가?)
file_path='../csv/2017'
file_list=os.listdir(file_path)

for file_name in file_list:
    #그러면 file_path에 마지막이 '/'로 끝나지 않으면 '/' 마지막에 추가하자.
    #endswith() : 문자의 마지막이 특정문자로 끝나는가? -> bool
    #file_path[-1] --> 문자열의 마지막을 출력
    if not(file_path.endswith('/')):
        file_path+='/'
        # file_path=file_path+'/'
        # print(file_path + file_name)
    # else:
        # print(file_path + file_name)
        # #참인 경우는 아무 행동도 하지 않는다.

    #반복 실행할때마다 전역변수를 새로 만든다.
    #파일의 이름이 201701_exepense_list.csv --> 앞에 '201701'만 추출하려면?
    #문자열 함수 split('_') --> 결과 list -> list의 첫번쩨 값
    #문자열을 특정영역까지 추출 str[:6]
    #전역변수의 이름은 df_201701, df_201702
    globals()[f'df_{file_name.split('_')[0]}']=pd.read_csv(file_path+file_name)

In [6]:
df_201703.info()

<class 'pandas.DataFrame'>
RangeIndex: 6114 entries, 0 to 6113
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   nid                6114 non-null   int64
 1   title              6114 non-null   str
 2   url                6114 non-null   str
 3   dept_nm_lvl_1      6114 non-null   str
 4   dept_nm_lvl_2      6114 non-null   str
 5   dept_nm_lvl_3      5373 non-null   str
 6   dept_nm_lvl_4      1552 non-null   str
 7   dept_nm_lvl_5      312 non-null    str
 8   exec_yr            6114 non-null   int64
 9   exec_month         6114 non-null   int64
 10  expense_budget     294 non-null    float64
 11  expense_execution  256 non-null    float64
 12  category           86 non-null     str
 13  dept_nm_full       6098 non-null   str
 14  exec_dt            6114 non-null   str
 15  exec_loc           6013 non-null   str
 16  exec_purpose       6113 non-null   str
 17  target_nm          6005 non-null   str
 18  payment_method     6102 non-null   str
 19  exec_amount        6114 non-null   int64
dtypes: float64(2), int64(4), str(14)
memory usage: 955.4 KB

In [7]:
df_201702.head(1)

,nid,title,url,dept_nm_lvl_1,dept_nm_lvl_2,dept_nm_lvl_3,dept_nm_lvl_4,dept_nm_lvl_5,exec_yr,exec_month,expense_budget,expense_execution,category,dept_nm_full,exec_dt,exec_loc,exec_purpose,target_nm,payment_method,exec_amount
0,11527154,2017년 2월 시의회사무처 보건복지전문위원실 업무추진비 집행내역,http://opengov.seoul.go.kr/public/11527154,의회사무처,보건복지전문위원실,NaN,NaN,NaN,2017,2,NaN,NaN,NaN,시의회사무처 보건복지전문위원실,2017-02-23 12:54,（주）스타벅스커피코 (중구 소공로),제272회 임시회 현장방문 논의 간담회,수석전문위원 외 5명,카드,30000

In [8]:
##같은 경로에서 12개의 데이터를 반복실행하면서 하나의 데이터프레이므로 결합
    #전역변수는 2개 생성
    #반복실행할때마다 데이터들을 유니언 켤합으로 행 결합
    #hint : list에 반복 실행할때마다 값을 추가하는 것과 같은 형식으로 구현
            #비어있는 리스트 생성 -> 반복 실행하면서 값을 .append()

#빈 리스트 대신 빈 데이터 프레임 생성
df=pd.DataFrame()
file_path='../csv/2017/'
file_list=os.listdir(file_path)

for file_name in file_list:
    #file_path에 마지막이 '/'가 있든 없든 그냥 붙인다.
    file_path+='/'
    print(file_path+file_name)
    #데이터 로드
    data=pd.read_csv(file_path+file_name)
    #유니언 결합(.append() 같은 행동)
    #첫번째 반복 : 빈 데이터프레임 +  201701 데이터 -> df에 대입
    #두번째 반복 : 201701 데이터 + 201702 데이터 -> df 대입
    #세번째 반복 : 201701~201702 + 201703 -> df 대입
    df=pd.concat(
        [df,data], axis=0
    )
df.reset_index(drop=True, inplace=True)

../csv/2017//201701_expense_list.csv
../csv/2017///201702_expense_list.csv
../csv/2017////201703_expense_list.csv
../csv/2017/////201704_expense_list.csv
../csv/2017//////201705_expense_list.csv
../csv/2017///////201706_expense_list.csv
../csv/2017////////201707_expense_list.csv
../csv/2017/////////201708_expense_list.csv
../csv/2017//////////201709_expense_list.csv
../csv/2017///////////201710_expense_list.csv
../csv/2017////////////201711_expense_list.csv
../csv/2017/////////////201712_expense_list.csv

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 70132 entries, 0 to 70131
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   nid                70132 non-null  int64
 1   title              70132 non-null  str
 2   url                70132 non-null  str
 3   dept_nm_lvl_1      70132 non-null  str
 4   dept_nm_lvl_2      70074 non-null  str
 5   dept_nm_lvl_3      61262 non-null  str
 6   dept_nm_lvl_4      17939 non-null  str
 7   dept_nm_lvl_5      3474 non-null   str
 8   exec_yr            70132 non-null  int64
 9   exec_month         70132 non-null  int64
 10  expense_budget     3108 non-null   float64
 11  expense_execution  2805 non-null   float64
 12  category           1259 non-null   str
 13  dept_nm_full       70053 non-null  str
 14  exec_dt            70132 non-null  str
 15  exec_loc           69360 non-null  str
 16  exec_purpose       70110 non-null  str
 17  target_nm          69597 non-null  str
 18  payment_method     69929 non-null  str
 19  exec_amount        70132 non-null  int64
dtypes: float64(2), int64(4), str(14)
memory usage: 10.7 MB

In [10]:
df=pd.DataFrame()
file_path='../csv/2019/'
file_list=os.listdir(file_path)

for file_name in file_list:
    file_path+='/'
    print(file_path+file_name)
    #2019년 폴더는 json 데이터이기 때문에 read_json() 사용
    data=pd.read_json(file_path+file_name)
    df=pd.concat(
        [df,data], axis=0
    )
df.reset_index(drop=True, inplace=True)
df.info()

../csv/2019//201901_expense_list.json
../csv/2019///201902_expense_list.json
../csv/2019////201903_expense_list.json
../csv/2019/////201904_expense_list.json
../csv/2019//////201905_expense_list.json
../csv/2019///////201906_expense_list.json
../csv/2019////////201907_expense_list.json
../csv/2019/////////201908_expense_list.json
../csv/2019//////////201909_expense_list.json
../csv/2019///////////201910_expense_list.json
../csv/2019////////////201911_expense_list.json
../csv/2019/////////////201912_expense_list.json
<class 'pandas.DataFrame'>
RangeIndex: 74207 entries, 0 to 74206
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   nid                74207 non-null  int64
 1   title              74207 non-null  str
 2   url                74207 non-null  str
 3   dept_nm_lvl_1      74207 non-null  str
 4   dept_nm_lvl_2      74207 non-null  str
 5   dept_nm_lvl_3      74207 non-null  str
 6   dept_nm_lvl_4      74207 non-null  str
 7   dept_nm_lvl_5      74207 non-null  str
 8   exec_yr            74207 non-null  int64
 9   exec_month         74207 non-null  int64
 10  expense_budget     2075 non-null   float64
 11  expense_execution  1598 non-null   float64
 12  category           74028 non-null  str
 13  dept_nm_full       74207 non-null  str
 14  exec_dt            74207 non-null  str
 15  exec_loc           74207 non-null  str
 16  exec_purpose       74207 non-null  str
 17  target_nm          74207 non-null  str
 18  payment_method     74207 non-null  str
 19  exec_amount        74207 non-null  int64
dtypes: float64(2), int64(4), str(14)
memory usage: 11.3 MB

In [15]:
#os 말고 glob 라이브러리
#glob 라이브러리 안에 glob() 함수
#glob(경로 + 파일의 형식(조건식)) -> 특정 경로 상에 특정 파일형식들만 따로 리스트화
glob('../csv/2021/*.json')
#os.listdir()과의 결과의 차이는? -> os는 파일의 이름으로 리스트 생성
#glob() -> 경로를 포함한 파일 리스트가 생성

['../csv/2021\\202101_expense_list.json',
 '../csv/2021\\202102_expense_list.json',
 '../csv/2021\\202103_expense_list.json',
 '../csv/2021\\202104_expense_list.json',
 '../csv/2021\\202105_expense_list.json',
 '../csv/2021\\202106_expense_list.json',
 '../csv/2021\\202107_expense_list.json',
 '../csv/2021\\202108_expense_list.json',
 '../csv/2021\\202109_expense_list.json',
 '../csv/2021\\202110_expense_list.json',
 '../csv/2021\\202111_expense_list.json',
 '../csv/2021\\202112_expense_list.json']

### 특정 경로의 파일들을 일괄적으로 로드하는 함수를 생성
1. 매개변수( 함수를 호출할 때마다 변할 수 있는 데이터 )
    - 경로 : file_path(필수 입력 항목)
    - 확장자 : file_ext(기본값 = csv)
    - 데이터 결합 여부 : output_type(기본값 = 'concat' || 'global')
    - 인코딩 엔진( 데이터가 한글이 들어간 경우 종종 에러 발생 ) : engine ( 기본값 = ' utf-8' | 'cp949' | 'euc_kr' )
2. 파일의 목록을 로드
    - os 라이브러리를 이용한다면 특정 확장자 필터
    - glob 라이브러리를 이용한다면 *.file_ext 필터    
3. 데이터 결합 여부에 따라 concat이라면 빈 데이터프레임 생성
    - global이라면 파일의 전역변수에서 사용할 넘버의 초기값 설정( file_idx = 1 )
4. 반복문을 실행하여 데이터를 로드
    - concat이면 데이터 결합
    - global이면 각각 데이터 변수에 대입
5. 결과를 되돌려준다.

In [28]:
def data_load(file_path,
              file_ext = 'csv',
              output_type = 'concat',
              engine ='utf-8'):
    #파일 path에 '/' 추가
    file_path+='/'
    file_list=os.listdir(file_path)
    #파일 목록이 file_ext와 ekfms 확장자가 포함되어있을 수 있다.
    #필터 -> 마지막이 file_ext와 같다면 리스트에 유지, 아니면 제거
    #case1
    file_list2=[x for x in file_list if x.endswith(file_ext)]
    # #case2
    # file_list2=[]
    # for x in file_list:
    #     if x.endswith(file_ext):
    #         #확장자가 csv와 같은 경우
    #         file_list2.append(x)

    #output_type이 concat이라면 빈 데이터프레임을 생성
    if output_type =='concat':
        result=pd.DataFrame()
    elif output_type =='global':
        #전역변수에서 사용할 넘버 생성
        vari_cnt=1
    else:
        #concat, global 이 아니라면 -> 에러발생 ValueError
        raise ValueError('output_type에는 concat이나 global만 사용이 가능합니다.')
        #에러기 발생 -> 함수도 종료

    #파일을 로드
    for file_name in file_list2:
        #file_ext에 따라 read_xxx() 선택
        if file_ext =='csv':
            df=pd.read_csv(file_path + file_name, encoding=engine)
        elif file_ext =='json':
            df=pd.read_json(file_path + file_name, encoding=engine)
        elif file_ext == 'xml':
            df=pd.read_xml(file_path + file_name, encoding=engine)
        # elif (file_ext == 'xlsx') or (file_ext=='xls') :
        elif file_ext in ['xlsx','xls']:
            #read_excel() 함수는 encoding 매개변수 존재하지 않는다.
            df=pd.read_excel(file_path + file_name)
        else:
            #위믜 모든 조건이 거짓인 경우 -> ValueError
            raise ValueError('file_ext에는 csv,json,xml,excel 확장자만 선택이 가능합니다.')
        
        #output_type에 따라 결합, 전역변수 저장
        if output_type == 'concat':
            result=pd.concat([result, df])
        else:
            #전역변수에 저장
            globals()[f'df_{vari_cnt}']=df.copy()
            print(f'df_{vari_cnt} 전역 변수가 생성')
            #vari_cnt 1씩 증가
            vari_cnt+=1
            
    #결과를 되돌려준다.
    try:
        #코드를 실행한다
        return result
    except:
        #try 코드가 실패하면 실행
        print('전역변수 생성 완료')

In [22]:
#함수 테스트
test_df=data_load(
    '../csv/2021',
    
)

In [23]:
test_df.info()

<class 'pandas.DataFrame'>
Index: 83819 entries, 0 to 10343
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   nid                83819 non-null  int64
 1   title              83819 non-null  str
 2   url                83819 non-null  str
 3   dept_nm_lvl_1      83819 non-null  str
 4   dept_nm_lvl_2      83819 non-null  str
 5   dept_nm_lvl_3      67930 non-null  str
 6   dept_nm_lvl_4      24831 non-null  str
 7   dept_nm_lvl_5      1473 non-null   str
 8   exec_yr            83819 non-null  int64
 9   exec_month         83819 non-null  int64
 10  expense_budget     60524 non-null  float64
 11  expense_execution  60524 non-null  float64
 12  category           980 non-null    str
 13  dept_nm_full       83819 non-null  str
 14  exec_dt            83819 non-null  str
 15  exec_loc           83185 non-null  str
 16  exec_purpose       83819 non-null  str
 17  target_nm          83467 non-null  str
 18  payment_method     83819 non-null  str
 19  exec_amount        83819 non-null  int64
 20  bimok              18427 non-null  str
dtypes: float64(2), int64(4), str(15)
memory usage: 14.1 MB

In [29]:
data_load('../csv/2021',output_type='global')

df_1 전역 변수가 생성
df_2 전역 변수가 생성
df_3 전역 변수가 생성
df_4 전역 변수가 생성
df_5 전역 변수가 생성
df_6 전역 변수가 생성
df_7 전역 변수가 생성
df_8 전역 변수가 생성
df_9 전역 변수가 생성
df_10 전역 변수가 생성
df_11 전역 변수가 생성
df_12 전역 변수가 생성
전역변수 생성 완료

In [31]:
#glob라이브러리를 이용해서 파일 목록 받고 파일이름에 접근하는 방법
file_path='../csv/2021/'
file_ext='json'

file_list=glob(f'{file_path}*.{file_ext}')
file_list

['../csv/2021\\202101_expense_list.json',
 '../csv/2021\\202102_expense_list.json',
 '../csv/2021\\202103_expense_list.json',
 '../csv/2021\\202104_expense_list.json',
 '../csv/2021\\202105_expense_list.json',
 '../csv/2021\\202106_expense_list.json',
 '../csv/2021\\202107_expense_list.json',
 '../csv/2021\\202108_expense_list.json',
 '../csv/2021\\202109_expense_list.json',
 '../csv/2021\\202110_expense_list.json',
 '../csv/2021\\202111_expense_list.json',
 '../csv/2021\\202112_expense_list.json']

In [36]:
for file_name in file_list:
    print(file_name)
    #os라이브러리에 경로와 파일이름을 나눠주는 함수
    # print(os.path.split(file_name))
    f_path,f_name=os.path.split(file_name)
    # print(f_name)
    #os라이브러리에서 파일이름과 확장자 나눠주는 함수
    name,ext= os.path.splitext(f_name)
    print(name)
    print(ext)
    break

../csv/2021\202101_expense_list.json
202101_expense_list
.json

## 우리가 만든 함수를 모듈화
- py 파일을 생성해서 함수를 넣고 저장